[bugfix] Fix inference of performance units
eth-cscs/reframe pull request #1460
Opened 2020-08-27 12:05 UTC by teojgo

Fixes #1447

2020-08-27 12:38 UTC, ekouts approved these changes

2020-08-27 12:46 UTC, teojgo commented
@MaximeVdB can you check if this solves your problem?

2020-08-27 19:58 UTC, vkarak requested changes

2020-08-27 19:58 UTC, vkarak commented on reframe/core/pipeline.py
> +                    ref_tuple = (0, None, None, unit or '(no unit specified)')
I would keep the unit as `None`. The JSON schema allows it to be so.

```suggestion
                    ref_tuple = (0, None, None, unit)
```

2020-08-27 19:58 UTC, vkarak commented on reframe/frontend/statistics.py
> +                unit = ref[4]
Here leave it as before.

2020-08-28 14:36 UTC, vkarak approved these changes
lgtm

2020-08-28 15:10 UTC, merged

2020-08-31 06:40 UTC, MaximeVdB commented
@teojgo Thanks, I did a quick test and this indeed solved the problem!