[feat] Add libpath option to bootstrap script
eth-cscs/reframe pull request #1495
Opened 2020-09-22 10:58 UTC by victorusu

This adds the `-p` option to pass a path to enable a different python path.

2020-09-23 20:51 UTC, vkarak requested changes

2020-09-23 20:51 UTC, vkarak commented on bootstrap.sh
> +echo "Setting PYTHONPATH to ${PYTHONPATH}"
Remove this line.

2020-09-23 20:51 UTC, vkarak commented on bootstrap.sh
> +export PYTHONPATH=$(pwd)/external:$(pwd)/external/${libpath}/python$pyver/site-packages:$PYTHONPATH
I guess you expect `libpath` to be an absolute path, so I would write this as

```suggestion
export PYTHONPATH=$(pwd)/external:$(pwd)/external${libpath}/python$pyver/site-packages:$PYTHONPATH
```

2020-09-23 20:51 UTC, vkarak commented on bootstrap.sh
> +    echo "  -p PATH  Use PATH as Python lib. Default /usr/lib"
```suggestion
    echo "  -L PATH  Prefix of Python libraries (default: '/usr/lib')"
```

2020-10-01 11:30 UTC, vkarak requested changes

2020-10-01 11:30 UTC, vkarak commented on bootstrap.sh
> +export PYTHONPATH=$(pwd)/external:$(pwd)/external${libpath}/python$pyver/site-packages:$PYTHONPATH
I think we should also a small check that the `libpath` is an absolute path and issue an error if not, or prefix it with `pwd`.

2020-10-01 14:26 UTC, victorusu commented
Further investigation showed that the problem displayed in #1492 is not related to the external dependencies, but to the way pip gets installed on the system.
In this case, I think that a better solution is to use the system- or package manager- provided version of pip.

2020-10-01 14:26 UTC, closed without merging