[Bugfix] Remove PrgEnv-pgi from fftw test on daint.
eth-cscs/reframe pull request #1507
Opened 2020-10-05 09:40 UTC by jjotero

FFTW checks are no longer building with PrgEnv-pgi on daint after the the pgi/20.x.x was made default.
Cray does not support FFTW with the PGI compiler, so we remove PrgEnv-pgi from the valid environments for this test on daint.

2020-10-06 08:04 UTC, victorusu commented
@jenkins-cscs retry all

2020-10-08 06:54 UTC, victorusu approved these changes
`lgtm`

2020-10-09 15:10 UTC, vkarak requested changes

2020-10-09 15:10 UTC, vkarak commented on cscs-checks/microbenchmarks/fft/fftw_benchmark.py
> +        elif self.current_system.name in {'tiger'}:
You can put Tiger in the same list as Daint and Dom.

2020-10-09 15:10 UTC, vkarak commented on cscs-checks/microbenchmarks/fft/fftw_benchmark.py
>              # compiler (Cray case #266199)
Can you remove also the Cray case number? 

```suggestion
            # Cray FFTW library is not supported for the PGI compiler
```

2020-10-13 16:06 UTC, vkarak approved these changes
lgtm

2020-10-13 22:29 UTC, merged