[doc] Remove session-id from basic tutorial report
eth-cscs/reframe pull request #1530
Opened 2020-10-12 13:55 UTC by teojgo

Fixes #1525

2020-10-12 20:15 UTC, vkarak requested changes

2020-10-12 20:15 UTC, vkarak commented on docs/tutorial_basics.rst
> +========================================== Tutorial 1: Getting Started with ReFrame ==========================================
This seems to have been changed by mistake.

2020-10-13 07:42 UTC, ekouts approved these changes

2020-10-13 15:42 UTC, vkarak approved these changes

2020-10-13 16:02 UTC, merged