[WIP] GridTools test update
eth-cscs/reframe pull request #1547
Opened 2020-10-22 12:21 UTC by ChristopherBignamini

2020-10-22 12:21 UTC, pep8speaks commented
Hello @ChristopherBignamini, Thank you for submitting the Pull Request!

* In the file [`cscs-checks/libraries/gridtools/gridtools_tests.py`](https://github.com/eth-cscs/reframe/blob/83bfaebd4676d247093f71b68dc9ac3ae610beb1/cscs-checks/libraries/gridtools/gridtools_tests.py):

> [Line 67:80](https://github.com/eth-cscs/reframe/blob/83bfaebd4676d247093f71b68dc9ac3ae610beb1/cscs-checks/libraries/gridtools/gridtools_tests.py#L67): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 79:80](https://github.com/eth-cscs/reframe/blob/83bfaebd4676d247093f71b68dc9ac3ae610beb1/cscs-checks/libraries/gridtools/gridtools_tests.py#L79): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 91:80](https://github.com/eth-cscs/reframe/blob/83bfaebd4676d247093f71b68dc9ac3ae610beb1/cscs-checks/libraries/gridtools/gridtools_tests.py#L91): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 109:80](https://github.com/eth-cscs/reframe/blob/83bfaebd4676d247093f71b68dc9ac3ae610beb1/cscs-checks/libraries/gridtools/gridtools_tests.py#L109): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)

Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2020-10-22 12:27 UTC, ChristopherBignamini commented
The way GridTools is tested (build and performances) has changed: instead of multiple executables they have now just one executable (perftests) that takes in input some parameters for domain size/number of iterations and the stencil type. Is there a way to avoid the re-building of the executable (perftests) for each test, if it already exists?

2020-10-22 12:52 UTC, victorusu commented
@ChristopherBignamini, yes. You can have a base test that compiles the code and multiple ones that depend on the former that use the compiled executable. The relevant documentation is [this](https://reframe-hpc.readthedocs.io/en/stable/dependencies.html).
Currently, you need to have all tests on the same partition, but after this [PR](https://github.com/eth-cscs/reframe/pull/1481) this won't be the case.

If I were you, I would for now implement on test that is based on `rfm.RegressionTest`, which compiles and runs a very simple test, like `perftest -h`, with partition `daint:gpu`, for instance.
All the other ones, then, will be based on `rfm.RunOnlyRegressionTest` with partition `daint:gpu` too. So they can work with the current setup.

2020-11-09 18:03 UTC, ChristopherBignamini commented
Thanks @victorusu , I've tried to split the build and the run steps into 2 different tests and I've added the dependency condition but I think I'm doing something wrong: the build tests seems to be ok, they run and pass, but when I try to run one of the run tests (that depends on the build ones) I get the error message 

/bin/reframe: could not resolve dependency: ('GridToolsGPURunCheck_horizontal_diffusion_gpu_horizontal_double', 'daint:gpu', 'builtin') -> 'GridToolsGPUBuildCheck'

Is there anything obvious I'm doing wrong? 

Also, question about design: I'd like to have a base class for the run only test, as I have for the build ones, and then derived classes for the GPU and CPU cases. Does it make sense wrt reframe guidelines? Thanks!

2020-11-09 20:07 UTC, vkarak commented
> Is there anything obvious I'm doing wrong?

@ChristopherBignamini Check this out: #1581. The problem is that test filtering happens now before the dependency resolution and it does not take into consideration the test dependencies. You have to select manually with `-n` the rest of the dependency chain...

2020-11-10 14:17 UTC, ChristopherBignamini commented
Thank @vkarak , now it seems to work.

2020-11-15 18:17 UTC, vkarak requested changes

2020-11-15 18:17 UTC, vkarak commented on cscs-checks/libraries/gridtools/gridtools_tests.py
>          # Check if this is a device check
I think this comment is stale.

2020-11-15 18:17 UTC, vkarak commented on cscs-checks/libraries/gridtools/gridtools_tests.py
> +        # Check if this is a device check
I think this comment is stale.

2020-11-15 18:17 UTC, vkarak commented on cscs-checks/libraries/gridtools/gridtools_tests.py
> +                        'timer': (0.0006, None, 0.1, 's')
How reliable are these timings, because they are rather small. Can you increase the test size to get higher numbers?

2020-11-15 18:17 UTC, vkarak commented on cscs-checks/libraries/gridtools/gridtools_tests.py
> +                        'timer': (9.0, None, 0.1, 's')
These numbers seem too round to be real, are they?

2020-12-01 19:03 UTC, vkarak requested changes

2020-12-01 19:03 UTC, vkarak commented on cscs-checks/libraries/gridtools/gridtools_tests.py
> +                'executable_opts': [
See my comment above about this.

2020-12-07 10:35 UTC, vkarak commented
@jenkins-cscs retry daint

2020-12-07 10:35 UTC, vkarak approved these changes

2020-12-07 11:38 UTC, merged