[feat] Add a more detailed listing of dependencies
eth-cscs/reframe pull request #1576
Opened 2020-11-04 13:49 UTC by ekouts

Fixes #1521.

Some output examples:
```
...
[List of matched checks]
- OSULatencyTest:
    Description:
      OSU latency test

...

    Tags:
      <none>

    Valid environments:
      gnu, pgi, intel

    Valid systems:
      daint:gpu

    Dependencies:
      OSUBuildTest

    Dependencies for current system:
      ('OSULatencyTest', 'daint:gpu', 'gnu') -> ('OSUBuildTest', 'daint:gpu', 'gnu')
      ('OSULatencyTest', 'daint:gpu', 'intel') -> ('OSUBuildTest', 'daint:gpu', 'intel')
      ('OSULatencyTest', 'daint:gpu', 'pgi') -> ('OSUBuildTest', 'daint:gpu', 'pgi')

- OSUBandwidthTest:
    Description:
      OSU bandwidth test

...

    Valid environments:
      gnu, pgi, intel

    Valid systems:
      daint:gpu

    Dependencies:
      OSUBuildTest

    Dependencies for current system:
      ('OSUBandwidthTest', 'daint:gpu', 'gnu') -> ('OSUBuildTest', 'daint:gpu', 'gnu')
      ('OSUBandwidthTest', 'daint:gpu', 'intel') -> ('OSUBuildTest', 'daint:gpu', 'intel')
      ('OSUBandwidthTest', 'daint:gpu', 'pgi') -> ('OSUBuildTest', 'daint:gpu', 'pgi')
...
```
or 
```
[List of matched checks]
- Test0:
    Description:
      Test0

    Environment modules:
      <none>

    Location:
      /path/to/reframe/unittests/resources/checks_unlisted/deps_simple.py

    Maintainers:
      <none>

    Node allocation:
      standard (1 task(s))

    Pipeline hooks:

    Tags:
      <none>

    Valid environments:
      e0, e1

    Valid systems:
      *

    Dependencies:
      <none>

    Dependencies for current system:
      <none>

- Test1_fully:
    Description:
      Test1_fully

    Environment modules:
      <none>

    Location:
      /path/to/reframe/unittests/resources/checks_unlisted/deps_simple.py

    Maintainers:
      <none>

    Node allocation:
      standard (1 task(s))

    Pipeline hooks:

    Tags:
      <none>

    Valid environments:
      e0, e1

    Valid systems:
      *

    Dependencies:
      Test0

    Dependencies for current system:
      <none>

- Test1_by_env:
    Description:
      Test1_by_env

    Environment modules:
      <none>

    Location:
      /path/to/reframe/unittests/resources/checks_unlisted/deps_simple.py

    Maintainers:
      <none>

    Node allocation:
      standard (1 task(s))

    Pipeline hooks:

    Tags:
      <none>

    Valid environments:
      e0, e1

    Valid systems:
      *

    Dependencies:
      Test0

    Dependencies for current system:
      <none>

- Test1_exact:
    Description:
      Test1_exact

    Environment modules:
      <none>

    Location:
      /path/to/reframe/unittests/resources/checks_unlisted/deps_simple.py

    Maintainers:
      <none>

    Node allocation:
      standard (1 task(s))

    Pipeline hooks:

    Tags:
      <none>

    Valid environments:
      e0, e1

    Valid systems:
      *

    Dependencies:
      Test0

    Dependencies for current system:
      <none>

- Test1_default:
    Description:
      Test1_default

    Environment modules:
      <none>

    Location:
      /path/to/reframe/unittests/resources/checks_unlisted/deps_simple.py

    Maintainers:
      <none>

    Node allocation:
      standard (1 task(s))

    Pipeline hooks:

    Tags:
      <none>

    Valid environments:
      e0, e1

    Valid systems:
      *

    Dependencies:
      Test0

    Dependencies for current system:
      <none>

Found 5 check(s)
Log file(s) saved in: '/var/folders/fk/vjppffg16jd1yv63wfbgsjd40000gp/T/rfm-p1kpe5su.log'
```

2020-11-04 13:49 UTC, pep8speaks commented
Hello @ekouts, Thank you for submitting the Pull Request!

* In the file [`reframe/frontend/cli.py`](https://github.com/eth-cscs/reframe/blob/8213fec5093f939cdacd9ca56c643f8f46f42acb/reframe/frontend/cli.py):

> [Line 107:80](https://github.com/eth-cscs/reframe/blob/8213fec5093f939cdacd9ca56c643f8f46f42acb/reframe/frontend/cli.py#L107): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 695:80](https://github.com/eth-cscs/reframe/blob/8213fec5093f939cdacd9ca56c643f8f46f42acb/reframe/frontend/cli.py#L695): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)

Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2020-11-04 14:04 UTC, ekouts commented
@jenkins-cscs retry all

2020-11-04 15:43 UTC, vkarak commented
What I can't understand from the output samples you posted is why the "Dependencies for current system" are empty for the second set of examples, when you have for example test dependencies.

2020-11-04 16:31 UTC, teojgo commented
> What I can't understand from the output samples you posted is why the "Dependencies for current system" are empty for the second set of examples, when you have for example test dependencies.

Executing this:
`./bin/reframe -C unittests/resources/settings.py  --system=sys0 -c unittests/resources/checks_unlisted/deps_simple.py -L`

looks good for me.

2020-11-04 16:34 UTC, ekouts commented
> What I can't understand from the output samples you posted is why the "Dependencies for current system" are empty for the second set of examples, when you have for example test dependencies.

@vkarak The environments `e0` and `e1` are not in the configuration, so no test is going to run in the end

2020-11-04 16:36 UTC, teojgo approved these changes

2020-11-04 16:37 UTC, vkarak commented
> @vkarak The environments e0 and e1 are not in the configuration, so no test is going to run in the end

This is a bit problematic and comes from the fact that the printing is based on tests not on the test cases. I was about to comment something related to that for your PR. Perhaps we can address also this problem. If the tests are not going to run, they should not be listed.

2020-11-04 16:40 UTC, ekouts commented
> This is a bit problematic and comes from the fact that the printing is based on tests not on the test cases. I was about to comment something related to that for your PR. Perhaps we can address also this problem. If the tests are not going to run, they should not be listed.

Okay, I can easily print only the checks that are included in the `index_of_deps`. Or do you prefer a different way to solve this issue?

2020-11-04 16:43 UTC, vkarak commented
I don't like the `index_of_deps` concept being computed outside and then just being passed along all the way down to `format_checks()`. The interface doesn't make sense. The `list_checks()` should take the test cases instead and derive the actual tests and dependencies from there. You build the dependency index privately inside that function or wherever it is actually needed.

2020-11-04 16:45 UTC, ekouts commented
Okay, I think I can pass only the testcases and infer the checks from there. This way we will only have the checks that will run

2020-11-04 17:06 UTC, vkarak requested changes

2020-11-04 17:06 UTC, vkarak commented on reframe/frontend/cli.py
> +    lines.append('    Dependencies for current system:')
Couldn't you add this as an element in `check_info`? And similarly to `fmt_list()`, have something like `fmt_deps()`.

2020-11-07 15:03 UTC, vkarak approved these changes
I did some small changes. Lgtm now.

2020-11-07 15:13 UTC, merged