[test] Remove retired system KESCH
eth-cscs/reframe pull request #1588
Opened 2020-11-09 13:45 UTC by kraushm

`kesch[:cn,pn]`  was removed from all tests and configuration files, since the system was taken out of production.

2020-11-14 18:42 UTC, vkarak requested changes
Lgtm overall. I have very minor comments and can you please remove "tiger" from everywhere as well?

2020-11-14 18:42 UTC, vkarak commented on cscs-checks/libraries/math/scalapack_compile_run.py
> +                              'dom:gpu']
Can't this fit in the line above?

2020-11-14 18:42 UTC, vkarak commented on cscs-checks/mch/automatic_arrays_acc.py
> +        self.valid_systems = ['daint:gpu', 'dom:gpu', 'tiger:gpu',
Remove also tiger, it's also retired.

2020-11-14 18:42 UTC, vkarak commented on cscs-checks/mch/collectives_halo.py
> +        self.valid_systems = ['dom:gpu', 'daint:gpu', 'tiger:gpu', 'arolla:cn',
Remove tiger as well.

2020-11-14 18:42 UTC, vkarak commented on cscs-checks/mch/collectives_halo.py
> +
Remove this line.

2020-11-14 18:42 UTC, vkarak commented on cscs-checks/mch/cuda_stress_test.py
> +        self.valid_systems = ['daint:gpu', 'dom:gpu', 'tiger:gpu',
Remove tiger as well.

2020-11-16 08:48 UTC, pep8speaks commented
Hello @kraushm, Thank you for updating!







































* In the file [`cscs-checks/microbenchmarks/cpu/dgemm/dgemm.py`](https://github.com/eth-cscs/reframe/blob/83c29194a0951f4872edf6e8e5c27b29fa9f08a5/cscs-checks/microbenchmarks/cpu/dgemm/dgemm.py):

> [Line 20:31](https://github.com/eth-cscs/reframe/blob/83c29194a0951f4872edf6e8e5c27b29fa9f08a5/cscs-checks/microbenchmarks/cpu/dgemm/dgemm.py#L20): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '['

















































Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2020-11-17 18:07 UTC, vkarak commented on cscs-checks/prgenv/openacc_checks.py
> +            if self.current_system.name == 'tsa':
Why is this only for Tsa?

2020-11-17 20:03 UTC, vkarak commented
@kraushm Can you also check why we have two failing tests?

2020-11-18 08:02 UTC, kraushm commented on cscs-checks/prgenv/openacc_checks.py
> +            if self.current_system.name == 'tsa':
Indeed, this was incomplete.

2020-11-19 12:37 UTC, vkarak approved these changes
lgtm

2020-11-19 12:38 UTC, vkarak commented
@jenkins-cscs retry daint

2020-11-19 14:58 UTC, merged