[bugfix] List inherited pipeline hooks with the `-L` option
eth-cscs/reframe pull request #1597
Opened 2020-11-13 14:47 UTC by ekouts

Closes #1566.

2020-11-14 12:45 UTC, vkarak requested changes

2020-11-14 12:45 UTC, vkarak commented on reframe/frontend/cli.py
> +                hooks[k].extend(v)
This is too esoteric to be exposed here. I suggest having a function at the class level the returns all the hooks.

2020-11-17 17:52 UTC, vkarak requested changes
This implementation is very close to this one:

https://github.com/eth-cscs/reframe/blob/67e66aad96ae751186c2efa58d319f34b6a394ba/reframe/core/pipeline.py#L84

I think we should have a class method that will iterate over the hooks walking through the `mro`. This will be used also in the place shown above.

2020-11-18 07:48 UTC, ekouts commented
@vkarak In the listing of the tests ith `-L` do we want to print disabled hooks as well?

2020-11-18 08:13 UTC, vkarak commented
> @vkarak In the listing of the tests with -L do we want to print disabled hooks as well?

I thought the same thing yesterday, but I don't have a strong opinion. For the moment I would say, whichever is the most straightforward to implement.

2020-11-18 22:12 UTC, vkarak commented on reframe/core/pipeline.py
> +    def hooks(cls):
```suggestion
    def pipeline_hooks(cls):
```

2020-11-18 22:12 UTC, vkarak commented on reframe/frontend/cli.py
> +            for k, v in type(check).hooks().items()
This works as well.

```suggestion
            for k, v in check.pipeline_hooks().items()
```

2020-11-19 17:22 UTC, vkarak approved these changes

2020-11-20 21:27 UTC, vkarak commented
@jenkins-cscs retry dom

2020-11-20 21:39 UTC, merged