[test] Add test for cray module variables
eth-cscs/reframe pull request #1598
Opened 2020-11-13 15:05 UTC by ekouts

This is a test to ensure that some cray modules include the variables `<module_name>_PREFIX` and `<module_name>_VERSION`. It will be more useful as soon as we get a new cdt so that we catch the missing variables early. Moreover, it would be nicer to skip the tests that we know are already failing, instead of making them succeed with the workaround.

2020-11-13 15:59 UTC, lucamar approved these changes
Thanks @ekouts, that's really useful!

2020-11-14 12:43 UTC, vkarak requested changes

2020-11-14 12:43 UTC, vkarak commented on cscs-checks/prgenv/environ_check.py
> +    def __init__(self, variant):
```suggestion
    def __init__(self, module_name):
```

2020-11-14 12:43 UTC, vkarak commented on cscs-checks/prgenv/environ_check.py
> +        mod_name = variant.upper().replace('-', '_')
```suggestion
        envvar_prefix = variant.upper().replace('-', '_')
```

2020-11-14 12:43 UTC, vkarak commented on cscs-checks/prgenv/environ_check.py
> +                             'cudatoolkit', 'gcc']):
You could explicitly empty the `valid_systems` for these modules and for CDT <= 20.10 directly in the `__init__()`. This way these tests will not even be run if the cdt is not the right one.

2020-11-16 15:29 UTC, vkarak approved these changes
lgtm

2020-11-16 16:00 UTC, merged