[feat] Print dependencies of tests in json report
eth-cscs/reframe pull request #1601
Opened 2020-11-16 08:47 UTC by ekouts

Closes #1414.

2020-11-17 22:18 UTC, vkarak requested changes
You should also bump the data version of the report here:

https://github.com/eth-cscs/reframe/blob/044397958f6cc6eba0a5272cd26dbbb03c0959d8/reframe/frontend/cli.py#L597

The idea is to bump the data format minor version every time we do an incremental change and the major version every time there is a breaking change.

2020-11-18 07:21 UTC, pep8speaks commented
Hello @ekouts, Thank you for updating!



* In the file [`reframe/frontend/statistics.py`](https://github.com/eth-cscs/reframe/blob/b6fcb6786f85cb1f47cb179f0186c73108dcb297/reframe/frontend/statistics.py):

> [Line 204:80](https://github.com/eth-cscs/reframe/blob/b6fcb6786f85cb1f47cb179f0186c73108dcb297/reframe/frontend/statistics.py#L204): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)

Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2020-11-18 07:41 UTC, rsarm approved these changes

2020-11-18 09:19 UTC, vkarak approved these changes
Lgtm, I only have a minor comment.

2020-11-18 09:19 UTC, vkarak commented on reframe/frontend/statistics.py
> +                        (d.check.name, d.partition.fullname, d.environ.name)
If I'm not mistaken you can write this simply as `(*d)`.

2020-11-18 09:24 UTC, vkarak commented on reframe/frontend/statistics.py
> +                        (d.check.name, d.partition.fullname, d.environ.name)
No, ignore this. The correct is `[*d]`, but it wouldn't work, because it returns the objects not the names.

2020-11-18 12:58 UTC, merged