[test] config for alps
eth-cscs/reframe pull request #1620
Opened 2020-11-26 07:23 UTC by jgphpc

2020-11-28 13:46 UTC, vkarak requested changes

2020-11-28 13:46 UTC, vkarak commented on config/cscs.py
> +                    'modules': [],
Remove this.

2020-11-28 13:46 UTC, vkarak commented on config/cscs.py
> +                        '--exclude=nid00[1512-1703,1768-1927]'
Can you add a `FIXME`  to remember updating this line?

2020-11-28 13:46 UTC, vkarak commented on config/cscs.py
> +                        # f'--constraint=mc',
Remove this.

2020-11-28 13:46 UTC, vkarak commented on config/cscs.py
> +                            'options': ['--bcast={path}']
Will we often need this?

2020-11-28 13:46 UTC, vkarak commented on config/cscs.py
> +                            'name': 'mem-per-cpu',
Will we often need this?

2020-11-28 13:46 UTC, vkarak commented on config/cscs.py
> +                        '--exclude=nid00[1000-1003,1006-1191,1256-1415]'
Same comment as above here.

2020-11-30 08:57 UTC, jgphpc commented
You're right, I can't comment inline if I am not a reviewer 
My comment was:
for large job, we point users to: https://user.cscs.ch/access/running/#large-jobs

2020-12-01 12:19 UTC, pep8speaks commented
Hello @jgphpc, Thank you for updating!

* In the file [`config/cscs.py`](https://github.com/eth-cscs/reframe/blob/013487b752e6b743945c2f541c7c564493a781c0/config/cscs.py):

> [Line 658:80](https://github.com/eth-cscs/reframe/blob/013487b752e6b743945c2f541c7c564493a781c0/config/cscs.py#L658): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (262 > 79 characters)
> [Line 683:80](https://github.com/eth-cscs/reframe/blob/013487b752e6b743945c2f541c7c564493a781c0/config/cscs.py#L683): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (182 > 79 characters)

Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2020-12-01 12:26 UTC, jgphpc commented
We have: `eiger:mc_lowmem` and `eiger:mc_himem`
I could also add the full partition: `eiger:mc` ?

2020-12-01 13:14 UTC, jgphpc commented
Looks like the constraint will not be set. The users will have to use the `--mem=` slurm flag.

2020-12-02 16:28 UTC, vkarak commented
> Looks like the constraint will not be set. The users will have to use the `--mem=` slurm flag.

So the way we have set up the configuration now is not correct. In such case, I would suggest to have a single partition and add the memory as a resource.

2020-12-03 12:54 UTC, vkarak requested changes
I have only a couple of minor comments that I could fix myself.

2020-12-03 12:54 UTC, vkarak commented on config/cscs.py
> +                            'name': 'mem-per-node',
```suggestion
                            'name': 'memory',
```

2020-12-03 12:54 UTC, vkarak commented on config/cscs.py
> +                            'name': 'mem-per-node',
```suggestion
                            'name': 'memory',
```

2020-12-03 12:54 UTC, vkarak commented on config/cscs.py
> +                'alps', 'eiger', 'rigi', 'pilatus'
I would only put the systems that we have defined here.

```suggestion
                'eiger', 'pilatus'
```

2020-12-03 12:54 UTC, vkarak commented on config/cscs.py
> +                'alps', 'eiger', 'rigi', 'pilatus'
Similarly here.

2020-12-05 11:24 UTC, jgphpc commented
I want to add `mem-per-cpu` to the config and here is why we need it:

> scontrol show conf

`DefMemPerCPU = 1000`

ok ?

2020-12-07 11:08 UTC, vkarak commented on config/cscs.py
> -                                '--mem={mem_per_node}'
This you can still keep it as `mem_per_node`. The name of the resource can have multiple options, that's they should not necessarily be the same.

2020-12-07 11:14 UTC, vkarak approved these changes
lgtm

2020-12-07 11:57 UTC, merged