[feat] Allow using colon separated paths with the `--module-path` option
eth-cscs/reframe pull request #1623
Opened 2020-11-26 22:51 UTC by vkarak

This is only the case when neither the `+` nor the `-` prefixes are used. The reason for this enhancement is to allow an easier manipulation of the path through. The unit tests are also adapted.

This blocks #1538, since the unit tests are broken in master on Dom.

2020-11-29 18:11 UTC, teojgo requested changes

2020-11-29 18:11 UTC, teojgo commented on unittests/test_cli.py
> +        module_path += f':{os.environ["MODULEPATH"]}'
Do this with the `suppress`

2020-11-30 13:04 UTC, teojgo approved these changes

2020-11-30 22:30 UTC, vkarak commented
@jenkins-cscs retry none

2020-11-30 22:37 UTC, merged