Ci generate pipeline new
eth-cscs/reframe pull request #1641
Opened 2020-12-03 21:23 UTC by victorusu

This is an initial draft of --ci-generate-pipeline feature.
The feature allows for creating GitLab dynamic pipelines.

missing:
[ ] fix overall variable names
[ ] fix `dependencies.topsort` to use the `_dfs` function
[ ] perform several small issues
[ ] test in real life Gitlab CI pipelines

2020-12-03 21:23 UTC, pep8speaks commented
Hello @victorusu, Thank you for submitting the Pull Request!

* In the file [`reframe/frontend/ci.py`](https://github.com/eth-cscs/reframe/blob/0551ff807e88f6bd491fb7f88bf1a015847b0762/reframe/frontend/ci.py):

> [Line 19:14](https://github.com/eth-cscs/reframe/blob/0551ff807e88f6bd491fb7f88bf1a015847b0762/reframe/frontend/ci.py#L19): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 20:12](https://github.com/eth-cscs/reframe/blob/0551ff807e88f6bd491fb7f88bf1a015847b0762/reframe/frontend/ci.py#L20): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 20:80](https://github.com/eth-cscs/reframe/blob/0551ff807e88f6bd491fb7f88bf1a015847b0762/reframe/frontend/ci.py#L20): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 31:80](https://github.com/eth-cscs/reframe/blob/0551ff807e88f6bd491fb7f88bf1a015847b0762/reframe/frontend/ci.py#L31): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 34:20](https://github.com/eth-cscs/reframe/blob/0551ff807e88f6bd491fb7f88bf1a015847b0762/reframe/frontend/ci.py#L34): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 35:21](https://github.com/eth-cscs/reframe/blob/0551ff807e88f6bd491fb7f88bf1a015847b0762/reframe/frontend/ci.py#L35): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 36:80](https://github.com/eth-cscs/reframe/blob/0551ff807e88f6bd491fb7f88bf1a015847b0762/reframe/frontend/ci.py#L36): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (160 > 79 characters)
> [Line 38:24](https://github.com/eth-cscs/reframe/blob/0551ff807e88f6bd491fb7f88bf1a015847b0762/reframe/frontend/ci.py#L38): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 39:24](https://github.com/eth-cscs/reframe/blob/0551ff807e88f6bd491fb7f88bf1a015847b0762/reframe/frontend/ci.py#L39): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 41:20](https://github.com/eth-cscs/reframe/blob/0551ff807e88f6bd491fb7f88bf1a015847b0762/reframe/frontend/ci.py#L41): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'



* In the file [`reframe/frontend/dependencies.py`](https://github.com/eth-cscs/reframe/blob/0551ff807e88f6bd491fb7f88bf1a015847b0762/reframe/frontend/dependencies.py):

> [Line 18:1](https://github.com/eth-cscs/reframe/blob/0551ff807e88f6bd491fb7f88bf1a015847b0762/reframe/frontend/dependencies.py#L18): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1



Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2020-12-03 21:27 UTC, victorusu commented
This PR suffers from the testcase vs test dependency syndrome. 😬 
Check this [gist](https://gist.github.com/victorusu/f04f2c17a6e053b17e2c62190df7d19e).

2021-02-02 10:01 UTC, vkarak commented on reframe/frontend/dependencies.py
> +    _dfs(graph)
I will remove the DFS traversal from here. If the graph has a cycle, it will loop forever. I will set the level inside the `validate_deps()`.

2021-02-02 17:46 UTC, vkarak requested changes

2021-02-02 17:46 UTC, vkarak commented on reframe/frontend/cli.py
> +            sys.exit(0)
I would prefer that this options just generated the the yaml file in stdout. Now the output is a bit irrelevant.

2021-02-05 22:38 UTC, vkarak commented on reframe/frontend/cli.py
> +            sys.exit(0)
I updated the output and I like it more now.

2021-02-05 22:39 UTC, vkarak approved these changes

2021-02-08 15:07 UTC, victorusu reviewed
I tested the feature and it is working perfectly! 
I liked the additional lint using the GitLab API.
I just have one comment about one sentence that has `them` too much. That's minor. IMHO, it could also go that way.

2021-02-08 15:07 UTC, victorusu commented on unittests/test_ci.py
> +    response = requests.post('https://gitlab.com/api/v4/ci/lint',
I liked it!

2021-02-08 15:28 UTC, vkarak commented on docs/tutorial_tips_tricks.rst
> +ReFrame will process them as usual, but instead of running them, it will generate the correct steps for running them in Gitlab.
Haha, indeed! I will fix that.

2021-02-08 19:37 UTC, merged