[bugfix] Respect cli modulepaths during module restore
eth-cscs/reframe pull request #1656
Opened 2020-12-14 16:03 UTC by teojgo

Fixes #1631

2020-12-14 16:04 UTC, teojgo commented
@jgphpc can you check if this works for you?

2020-12-14 21:07 UTC, vkarak requested changes
As for testing, you can create a temporary module collection as we do in the module collection unit tests and play with the module paths.

2020-12-14 21:07 UTC, vkarak commented on reframe/core/modules.py
> +        self._module_paths_removed = []
I would have a single list of tuples here of the form: `[('+', 'path/added'), ('-', '/path/removed')]`. This way you keep the sequence of additions and deletions and be completely sure that you preserve the same behaviour.

2020-12-15 19:21 UTC, vkarak approved these changes
lgtm. I only have a minor cosmetic comment.

2020-12-15 19:21 UTC, vkarak commented on reframe/core/modules.py
> +                instructions += [f'module {operation} {mp}']
```suggestion
                cmds += [f'module {operation} {mp}']
```

2020-12-15 20:57 UTC, merged