[wip] Add Bash completion support to ReFrame
eth-cscs/reframe pull request #1685
Opened 2021-01-14 15:38 UTC by rsarm

Closes #725

2021-01-14 15:55 UTC, rsarm commented
So far this is a bit of a poc. On Daint this can be tested with
```
module load reframe
. ac-reframe.sh
```
Currently, this supports completion of command line options:
```
$> reframe [TAB][TAB]
-c               --help                    --module-mappings         -R                        -t
-C               --ignore-check-conflicts  --module-path             --recursive               --tag
--checkpath      -J                        -n                        --report-file             --timestamp
--config-file    --job-option              --name                    --restore-session         -u
--cpu-only       --keep-stage-files        --nocolor                 --run                     --unload-module
(...)
```
files and directories for `-c`, `--checkpath`, `-C` and `--config-file`:
```
$> reframe -r -c cscs-checks/[TAB][TAB]
analytics/           apps/            compile/         libraries/       mch/            
microbenchmarks/     prgenv/          system/          tools/ 
```
and test names given a directory or file through the `-c` option
```
$> reframe -r -c cscs-checks/apps/quantumespresso/ -n  [TAB][TAB] QuantumESPRESSO
$> reframe -r -c cscs-checks/apps/quantumespresso/ -n QuantumESPRESSO[TAB][TAB]
QuantumESPRESSOCpuCheck_large_maint  QuantumESPRESSOCpuCheck_small_maint  
QuantumESPRESSOGpuCheck_large_maint  QuantumESPRESSOGpuCheck_small_maint
QuantumESPRESSOCpuCheck_large_prod   QuantumESPRESSOCpuCheck_small_prod   
QuantumESPRESSOGpuCheck_large_prod   QuantumESPRESSOGpuCheck_small_prod
```

2021-02-04 22:17 UTC, vkarak requested changes
I just played a bit with this PR. These are some problems I've noticed:

- Strange characters when auto-completing command-line options:
```
$ reframe --c
--checkpath^[[m^[[K  --config-file^[[m^[[K--cpu-only^[[m^[[K
```
- The same happens when it auto-completes the command-line:

```
$ reframe --checkpath^[\[m^[\[K
```

2021-02-05 07:52 UTC, rsarm commented
@vkarak in which terminal did you try?

2021-02-05 08:25 UTC, vkarak commented
@rsarm I tried on my Mac's bash. But then I started playing with `argcomplete` and tried to understand why it doesn't work in our case. Actually, it seems that it can work with our setup, but there is something that we still need to figure out. If you run the following Python script (using our `ArgParser`, slightly modified (see below)) it works:

```python
#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK

import argcomplete
from argcomplete.completers import EnvironCompleter

import reframe.frontend.argparse as argparse


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--env-var1").completer = EnvironCompleter
    parser.add_argument("--env-var2").completer = EnvironCompleter
    parser.add_argument("--env-var3").completer = EnvironCompleter
    options = parser.parse_args()


if __name__ == '__main__':
    main()

```

And I added the following two lines in our `ArgParser`:

```diff
@@ -257,6 +257,9 @@ class ArgumentParser(_ArgumentHolder):
         `add_argument()` call. If no default value was specified either, the
         attribute will be set to `None`.'''

+        import argcomplete
+        argcomplete.autocomplete(self._holder)
+
         # We always pass an empty namespace to our internal argparser and we do
         # the namespace resolution ourselves. We do this, because we want the
         # newly parsed options to completely override any options defined in
```

Now if I try to run `./bin/reframe` (with `PYTHON_ARGCOMPLETE_OK`), which uses the exact same parser it doesn't work. I think we need to replicate the file structure of `./bin/reframe` and `cli.py` with completely stripped down versions and see why it can't pick the autocompletion in that case, because in principle the trick above can make it work. So it must be something in-between that is happening.

2021-02-06 23:04 UTC, vkarak approved these changes
lgtm

2021-02-08 10:08 UTC, teojgo approved these changes

2021-02-08 10:51 UTC, merged