[test] Fix total energy reference value of QE GPU small on Dom
eth-cscs/reframe pull request #1686
Opened 2021-01-14 18:14 UTC by lucamar

The fix applies to the modulefile `QuantumESPRESSO/6.6a2-CrayPGI-20.10-cuda`: the total energy of the small test case changed with the new Cray Programming Environment 20.10 and the new cudatoolkit 11.0.

2021-01-14 18:59 UTC, lucamar commented
I have temporarily increased the energy difference allowed by the sanity check, otherwise the test would fail either on Dom or Piz Daint until we have different default Cray PE and CUDA version on the two systems, since the total energy difference is ~ `8e-08`: 
https://jenkins.cscs.ch/blue/organizations/jenkins/ReframeCI/detail/ReframeCI/4450/pipeline

2021-01-15 11:00 UTC, pep8speaks commented
Hello @lucamar, Thank you for updating!

* In the file [`cscs-checks/apps/quantumespresso/quantumespresso_check.py`](https://github.com/eth-cscs/reframe/blob/0df6109bd93688d5b475b92caede40dd13eb6ad1/cscs-checks/apps/quantumespresso/quantumespresso_check.py):

> [Line 59:1](https://github.com/eth-cscs/reframe/blob/0df6109bd93688d5b475b92caede40dd13eb6ad1/cscs-checks/apps/quantumespresso/quantumespresso_check.py#L59): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 60:1](https://github.com/eth-cscs/reframe/blob/0df6109bd93688d5b475b92caede40dd13eb6ad1/cscs-checks/apps/quantumespresso/quantumespresso_check.py#L60): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 115:1](https://github.com/eth-cscs/reframe/blob/0df6109bd93688d5b475b92caede40dd13eb6ad1/cscs-checks/apps/quantumespresso/quantumespresso_check.py#L115): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 116:1](https://github.com/eth-cscs/reframe/blob/0df6109bd93688d5b475b92caede40dd13eb6ad1/cscs-checks/apps/quantumespresso/quantumespresso_check.py#L116): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented

Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2021-01-15 12:00 UTC, teojgo requested changes
Just allign the FIXME with the following line

2021-01-15 12:29 UTC, teojgo approved these changes

2021-01-15 13:06 UTC, teojgo commented
@jenkins-cscs retry all

2021-01-18 10:14 UTC, teojgo requested changes

2021-01-18 10:14 UTC, teojgo commented on cscs-checks/apps/quantumespresso/quantumespresso_check.py
> +            # FIXME temporarily increase energy difference
```suggestion
            # FIXME temporarily increase energy difference
```

2021-01-18 10:24 UTC, teojgo approved these changes

2021-01-18 11:47 UTC, lucamar commented
The test `unittests/test_utility.py` failed on Eiger, however there is `Lmod` on the system:
```
unittests/test_utility.py:270: AssertionError
[...]
SKIPPED [2] unittests/test_utility.py:1406: could not find a sane TMod installation: [Errno 2] No such file or directory: 'modulecmd': 'modulecmd'
SKIPPED [2] unittests/test_utility.py:1406: could not find a sane TMod4 installation: [Errno 2] No such file or directory: 'modulecmd': 'modulecmd'
FAILED unittests/test_utility.py::test_git_repo_exists - AssertionError: asse...
```

2021-01-18 12:47 UTC, vkarak commented
@jenkins-cscs retry eiger

2021-01-18 12:47 UTC, vkarak approved these changes
lgtm

2021-01-19 09:50 UTC, merged