[doc] Expand tutorials
eth-cscs/reframe pull request #1692
Opened 2021-01-19 09:22 UTC by vkarak

2021-01-20 15:33 UTC, jgphpc commented
docs/tutorial_advanced.rst 
typo on line 158 (`configuration`)

2021-01-20 15:34 UTC, teojgo commented on docs/tutorial_basics.rst
> +
Remove this line

2021-01-20 15:51 UTC, jgphpc commented on docs/tutorial_advanced.rst
> +The most common case is to pass arguments to the launcher command that you cannot pass them as job options.
```suggestion
that you cannot normally pass as job options.
```

2021-01-20 15:53 UTC, jgphpc commented on docs/tutorial_advanced.rst
> +- Replacing the launcher
remove this line ?

2021-01-20 17:48 UTC, teojgo commented on docs/tutorial_advanced.rst
>  Flexible Regression Tests
Maybe add also here that flexible tests should run with the serial execution policy.

2021-01-21 06:36 UTC, jgphpc commented on docs/tutorial_tips_tricks.rst
> +   ./bin/reframe -C tutorials/config/settings.py -c tutorials/basics/hello/hello2.py -r
`-l -v` instead of -r ?

2021-01-21 15:27 UTC, vkarak commented on tutorials/advanced/jobopts/eatmemory.py
> +        self.job.options = ['--mem=2000']
I leave this for the moment until we fix #1700.

2021-01-21 15:45 UTC, teojgo requested changes

2021-01-21 15:45 UTC, teojgo commented on docs/tutorial_tips_tricks.rst
> +ReFrame tests are Python classes inside Python source files, so the usual debugging techniques for Python apply, but the ReFrame frontend will filter some errors and stack traces by default in order
```suggestion
ReFrame tests are Python classes inside Python source files, so the usual debugging techniques for Python apply, but the ReFrame frontend will filter some errors and stack traces by default in order to keep the output clean.
```

2021-01-21 15:45 UTC, teojgo commented on docs/tutorial_tips_tricks.rst
> +You can see all the different phase ReFrame's frontend goes through when loading a test.
```suggestion
You can see all the different phases ReFrame's frontend goes through when loading a test.
```

2021-01-21 15:45 UTC, teojgo commented on docs/tutorial_tips_tricks.rst
> +First "strange" thing to notice in this log is that ReFrame picked the generic system configuration.
```suggestion
The first "strange" thing to notice in this log is that ReFrame picked the generic system configuration.
```

2021-01-21 15:45 UTC, teojgo commented on docs/tutorial_tips_tricks.rst
> +Assume you have a test loads a ``gromacs`` module:
```suggestion
Assume you have a test that loads a ``gromacs`` module:
```

2021-01-21 15:45 UTC, teojgo commented on docs/tutorial_tips_tricks.rst
> +Every time ReFrame will try to load the ``gromacs`` module, it will replace it with ``gromacs/2020.5``.
```suggestion
Every time ReFrame tries to load the ``gromacs`` module, it will replace it with ``gromacs/2020.5``.
```

2021-01-21 15:45 UTC, teojgo commented on docs/tutorial_tips_tricks.rst
> +If you are running ReFrame regularly as part of a continuous testing procedure you might not want to generate it alerts for transient failures.
```suggestion
If you are running ReFrame regularly as part of a continuous testing procedure you might not want to it to generate alerts for transient failures.
```

2021-01-21 15:45 UTC, teojgo commented on docs/tutorial_tips_tricks.rst
> +The failed test cases will not retried immediately after they have failed, but rather at the end of the run session.
```suggestion
The failed test cases will not be retried immediately after they have failed, but rather at the end of the run session.
```

2021-01-21 15:45 UTC, teojgo commented on docs/tutorial_tips_tricks.rst
> +There is a little tweak, though, for this to work:
```suggestion
There is a little prerequisite, though, for this to work:
```

2021-01-21 15:45 UTC, teojgo commented on docs/tutorial_advanced.rst
> +We have briefly looked into parameterized tests in :doc:`tutorial_basics` where we parameterized the "Hello, World!" test based on the program language.
```suggestion
We have briefly looked into parameterized tests in :doc:`tutorial_basics` where we parameterized the "Hello, World!" test based on the programming language.
```

2021-01-21 15:45 UTC, teojgo commented on docs/tutorial_advanced.rst
> +In this example, we will parameterize the last version of the STREAM test from the :doc:`tutorial_basics` by changing the array size, so as to check bandwidth of the different cache levels.
```suggestion
In this example, we will parameterize the last version of the STREAM test from the :doc:`tutorial_basics` by changing the array size, so as to check the bandwidth of the different cache levels.
```

2021-01-21 15:45 UTC, teojgo commented on docs/tutorial_advanced.rst
> +A parameterized test needs to be decorated with the :func:`@parameterized_test <reframe.core.decorators.parameterized_test>` decorator and has its constructor accepting a set of parameters.
```suggestion
A parameterized test needs to be decorated with the :func:`@parameterized_test <reframe.core.decorators.parameterized_test>` decorator and define its constructor to accept a set of parameters.
```

2021-01-21 15:45 UTC, teojgo commented on docs/tutorial_advanced.rst
> +We compiled and run a program that consumes all the available memory of the node, but we want to restrict the available memory with the ``--mem`` option.
```suggestion
We compiled and ran a program that consumes all the available memory of the node, but we want to restrict the available memory with the ``--mem`` option.
```

2021-01-21 15:45 UTC, teojgo commented on docs/tutorial_advanced.rst
> +
Delete these empty lines

2021-01-22 15:17 UTC, teojgo reviewed
Change also the pattern in: https://github.com/eth-cscs/reframe/blob/7c7297c1b7ada2b99926f5cef7daf0677871b294/tutorials/advanced/flexnodes/flextest.py#L20

to `^nid\d+$` so that the job report is not taken into account in the pattern search.

2021-01-22 15:24 UTC, vkarak commented on docs/tutorial_tips_tricks.rst
> +There is a little tweak, though, for this to work:
I kind of prefer the "tweak" here.

2021-01-22 15:28 UTC, vkarak commented on docs/tutorial_advanced.rst
> +A parameterized test needs to be decorated with the :func:`@parameterized_test <reframe.core.decorators.parameterized_test>` decorator and has its constructor accepting a set of parameters.
I changed that a bit.

2021-01-22 15:29 UTC, vkarak commented on docs/tutorial_advanced.rst
> +
Just one of them.

2021-01-22 15:37 UTC, vkarak reviewed
@victorusu We will need a page with instructions. Should we use the wiki for this?

2021-01-22 15:37 UTC, vkarak commented on tutorials/config/eum21.py
> +import reframe.utility.osext as osext
This is unused, but I will remove it.

2021-01-22 15:37 UTC, vkarak commented on tutorials/config/eum21.py
> +            'resourcesdir': '/apps/reframe/reframe-resources/',
No resourcesdir.

2021-01-22 15:37 UTC, vkarak commented on tutorials/config/eum21.py
> +                        'builtin-gcc',
Why the `builtin-gcc`?

2021-01-22 15:37 UTC, vkarak commented on tutorials/config/eum21.py
> +                        'PrgEnv-gnu-nompi'
No Cray notation! You should use the tutorial config as a baseline for this config.

2021-01-22 15:37 UTC, vkarak commented on tutorials/config/eum21.py
> +    'modes': [
No modes!

2021-01-22 15:37 UTC, vkarak commented on tutorials/config/eum21.py
> +    ]
No. Please use the `tutorials/config/settings.py` as a baseline.

2021-01-24 18:23 UTC, vkarak commented on tutorials/config/eum21.py
> +                        'builtin-gcc',
Now I understand it. It's fine.

2021-01-25 07:56 UTC, ekouts approved these changes

2021-01-25 09:54 UTC, teojgo approved these changes

2021-01-25 17:39 UTC, pep8speaks commented
Hello @vkarak, Thank you for updating!



























* In the file [`tutorials/deps/osu_benchmarks.py`](https://github.com/eth-cscs/reframe/blob/92fd50f5b1b0c32556ceaa92017ed8bfe21549ea/tutorials/deps/osu_benchmarks.py):

> [Line 120:80](https://github.com/eth-cscs/reframe/blob/92fd50f5b1b0c32556ceaa92017ed8bfe21549ea/tutorials/deps/osu_benchmarks.py#L120): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)

Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2021-01-26 10:56 UTC, merged