Load cdt-cuda in dom for GPU cases
eth-cscs/reframe pull request #1694
Opened 2021-01-19 14:32 UTC by jjotero

Extended hook for `dom:gpu` so that the tests under `microbenchmarks/gpu` load the `cdt-cuda` module.

2021-01-19 15:48 UTC, teojgo requested changes
Better use `craype-accel-nvidia60` for dom/daint.

2021-01-19 20:55 UTC, vkarak requested changes
I agree with @teojgo's comment.

2021-01-20 09:11 UTC, jjotero commented
Done. I'll update also the new tests in PR #1687.

2021-01-20 09:11 UTC, teojgo approved these changes

2021-01-20 10:30 UTC, vkarak approved these changes

2021-01-20 10:31 UTC, merged