[test] Constrain flexible node allocation on the HPCG check
eth-cscs/reframe pull request #1720
Opened 2021-01-29 13:09 UTC by jjotero

The HPCG test requires the number of nodes to be factored into `N=nx*ny*nx`, where `max(nx, ny, nz)/min(nx, ny, nz) >= 8`.
Thus, since this case is a flexible test, some guidance is needed to have the 'raw' slurm node guess educated into something the HPCG tests can work with (for example, if the number of available nodes in the system is a prime number, the above factorisation is impossible).
 
This PR solves this issue by adding a hook into the `pre_run` stage of these tests. The hook simply does the node guess in advance and makes sure that the number of nodes is a sensible one. With this 'constrained' number of nodes we set `self.num_tasks` in the test, which avoids reframe to query for the available number of nodes again at a later stage.

2021-01-29 13:09 UTC, pep8speaks commented
Hello @jjotero, Thank you for submitting the Pull Request!

* In the file [`cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py`](https://github.com/eth-cscs/reframe/blob/ea6eac5ce8664dda517e2903f1b0ad9a11c89d0c/cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py):

> [Line 20:9](https://github.com/eth-cscs/reframe/blob/ea6eac5ce8664dda517e2903f1b0ad9a11c89d0c/cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py#L20): [E306](https://duckduckgo.com/?q=pep8%20E306) expected 1 blank line before a nested definition, found 0
> [Line 25:21](https://github.com/eth-cscs/reframe/blob/ea6eac5ce8664dda517e2903f1b0ad9a11c89d0c/cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py#L25): [E228](https://duckduckgo.com/?q=pep8%20E228) missing whitespace around modulo operator

Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2021-01-31 18:07 UTC, vkarak requested changes
Another thing is that we would need to set `self.num_tasks = -8` in the tests. As far as I understood this is the minimum number of tasks, right? This would cause `guess_num_tasks()` to fail if it can't find enough nodes to satisfy this. In all our examples, however, since we always use one task per core and all our systems have more than 8 cores, but we can set this for correctness.

2021-02-01 11:31 UTC, jjotero commented
I just checked and the test seems to run fine with only one node (and 2 tasks per node). The only restriction I could find is the aspect ratio must be above 0.125 when doing the domain decomposition. But that's automatically satisfied for any node count below 10.

2021-02-01 12:27 UTC, vkarak approved these changes
lgtm

2021-02-01 12:46 UTC, merged