[feat] Comply with the semantic versioning spec
eth-cscs/reframe pull request #1761
Opened 2021-02-10 12:38 UTC by vkarak

This PR also adds the following:

- Expand deprecation message function to issue deprecation warnings in future releases.
- Old style of version specification is set to deprecate for 3.5.0

TODO:

- [ ] Update documentation of the `@required_version` decorator.

NOTE: The CI will fail due to an irrelevant reason. A separate PR will fix that (it's Gitlab CI lint failure)

2021-02-10 12:50 UTC, teojgo requested changes

2021-02-10 12:50 UTC, teojgo commented on reframe/utility/versioning.py
> +    import re
Remove this

2021-02-10 12:50 UTC, teojgo commented on unittests/test_versioning.py
> +import semver
Remove this

2021-02-16 16:07 UTC, teojgo approved these changes

2021-02-16 16:24 UTC, vkarak commented
@teojgo The `wheelvalidation` works ;-) I will fix the PR.

2021-02-16 22:59 UTC, merged