[bugfix] Make attrs utility function pass when an AttributeError is raised
eth-cscs/reframe pull request #1802
Opened 2021-02-22 17:28 UTC by jjotero

When the `LoggerAdapter` class calls the `attrs` method from `reframe/utility/__init__.py` it retrieves the values of the data descriptors from an object.

With the recent addition of the `variable` built-in, variables can be set as `required` (undefined), which means that a call to `getattr` on these variables will raise an `AttributeError`. When any of these required variables is not set when `LoggerAdapter` class attempts to fetch all the descriptors from a test, this raises a very ugly `AttributeError`.

For this reason, this `attrs` function from utility must pass if its call to `getattr` raises an `AttributeError`.

The unit test has also been changed accordingly.

2021-02-22 23:05 UTC, vkarak requested changes

2021-02-23 08:58 UTC, jjotero commented on reframe/utility/__init__.py
> +            if inspect.isdatadescriptor(cls.__dict__[attr]):
Using `items()` here will try to access the value of the descriptor and raise the `AttributeError`.

2021-02-23 09:37 UTC, jjotero commented on reframe/utility/__init__.py
> +                    pass
Comments pushed.

2021-02-23 09:42 UTC, ekouts approved these changes

2021-02-23 10:01 UTC, vkarak approved these changes
lgtm

2021-02-23 12:39 UTC, vkarak commented
@jenkins-cscs retry dom

2021-02-23 13:06 UTC, merged