[feat] Add option to include commands in the job script before the modules are loaded
eth-cscs/reframe pull request #1803
Opened 2021-02-23 08:36 UTC by rsarm

Closes #1734

2021-02-26 14:49 UTC, teojgo requested changes
We wil also need a unittest for this.

2021-02-26 14:56 UTC, ekouts commented on reframe/core/pipeline.py
> +    #: .. versionadded:: 3.5
```suggestion
    #: .. versionadded:: 3.5.0
```
I think the version should be `3.5.0`, but I am not sure.

2021-03-01 14:46 UTC, vkarak requested changes
I don't think this PR is correct in its principle. These commands are partition specific and not test-specific. I don't think we should anything to the test API. Instead, these commands must be part of the configuration of the partition. This is what I understand from the issue: every script submitted to that partition needs to have a `module purge`.

2021-03-03 12:43 UTC, vkarak requested changes
The implementation looks good. I have a suggestion about the name of the option and we still need the following:

1. A unit test or adapt `test_prepare`
2. Documentation (both in the configuration reference and [here](https://reframe-hpc.readthedocs.io/en/stable/tutorial_advanced.html#customizing-the-test-job-script) (we need to update the script template).

2021-03-03 12:43 UTC, vkarak commented on reframe/core/pipeline.py
> +                    self._current_partition.preload_cmds,
I would rename the commands everywhere to

```suggestion
                    self._current_partition.prepare_cmds,
```

2021-03-03 12:43 UTC, vkarak commented on reframe/core/schedulers/__init__.py
> +    def prepare(self, commands, environs=None, preload_cmds=[], **gen_opts):
We need to add a unit test for that or adapt the `test_prepare` unit test.

2021-03-03 14:50 UTC, teojgo commented
@rsarm, @vkarak do you think that this is the case for both build/run scripts? I have the feeling that this is needed only for the compute nodes, at least on #1734

2021-03-03 17:00 UTC, vkarak commented
@teojgo I think you are correct here. We should use it also for the build scripts, since for the moment we say that we submit to the same partition, so users would expect to see that in the build scripts, too, since they submit in the same partition.

2021-03-03 17:02 UTC, teojgo commented
> @teojgo I think you are correct here. We should use it also for the build scripts, since for the moment we say that we submit to the same partition, so users would expect to see that in the build scripts, too, since they submit in the same partition.

Yes for the moment it is used for both.

2021-03-04 13:18 UTC, vkarak approved these changes
lgtm

2021-03-04 13:25 UTC, teojgo approved these changes

2021-03-04 13:27 UTC, ekouts approved these changes

2021-03-04 13:53 UTC, vkarak commented
@branfosj With this feature you will now be able to define your partition as follows:

```python
{
    'name': 'mypart',
    'scheduler': 'slurm',
    'launcher': 'srun',
    'prepare_cmds': ['module purge'],
    'modules': ['bluebear']
}
```

The `prepare_cmds` will always be emitted before any commands that load the test environment. Let us know if this is sufficient.

2021-03-04 16:05 UTC, branfosj commented
Thanks

2021-03-04 17:36 UTC, merged