[feat] Support parameter and variable access directly from the class body
eth-cscs/reframe pull request #1806
Opened 2021-02-23 14:40 UTC by jjotero

This PR implements the attribute access to variables and parameters directly from the class body. Prior to this PR, an attempt to access either variables or parameters from the class body resulted in a `NameError` since none of these built-ins are stored in the public namespace from the class. This PR not only implements the access to these items, but also provides a more robust error handling in case of erroneous user input:

- Accessing a required (undefined) variable in the class body will raise a `ValueError`:
```python
class Foo(rfm.RegressionMixin):
    v = variable(str)
    x = f'{v}' # This will raise an error because `v` has no value
```
- Accessing a defined variable will return its default value:
```python
class Foo(rfm.RegressionMixin):
    v = variable(int, value=4)
    x = v + 1 # this sets x to 5
```
- Accessing a parameter directly from the class body is disallowed.
```python
class Foo(rfm.RegressionMixin):
    p = parameter([1, 2, 3])
    x = f'{p}' # This raises an error. Here `P` is a TestParam object, not a test parameter.
```

2021-02-23 18:50 UTC, vkarak requested changes

2021-02-23 18:50 UTC, vkarak commented on reframe/core/pipeline.py
> +class RegressionTest(jsonext.JSONSerializable, RegressionMixin):
I would put `RegressionMixin` first in the row here.

2021-02-23 18:50 UTC, vkarak commented on reframe/core/meta.py
> +                            f'variable {key!r} does not have an assigned value'
```suggestion
                            f'variable {key!r} is not assigned a value'
```

2021-02-23 18:50 UTC, vkarak commented on reframe/core/meta.py
> +            except Exception as err:
Why not just a `KeyError`?

2021-02-23 18:50 UTC, vkarak commented on reframe/core/meta.py
> +                        raise err
```suggestion
                        raise err from None
```

2021-02-24 08:20 UTC, jjotero commented on reframe/core/meta.py
> +            except Exception as err:
Yeah, makes sense. Changed.

2021-02-24 09:16 UTC, vkarak approved these changes
lgtm

2021-02-24 09:21 UTC, ekouts approved these changes

2021-02-24 09:30 UTC, teojgo approved these changes

2021-02-24 09:31 UTC, merged