[test] Use conformant semantic version in all tests
eth-cscs/reframe pull request #1824
Opened 2021-02-26 15:41 UTC by teojgo

2021-03-01 11:05 UTC, teojgo commented
@jenkins-cscs retry all

2021-03-03 16:57 UTC, vkarak commented
@teojgo For this one, we need to make sure that the versions in the decorator are correct. I'm not sure that we maintained correctly these version numbers...

2021-03-03 16:58 UTC, teojgo commented
> @teojgo For this one, we need to make sure that the versions in the decorator are correct. I'm not sure that we maintained correctly these version numbers...

Ok, I can look at the history to see when each test was introduced.

2021-03-05 10:21 UTC, vkarak requested changes
As discussed, I think it's better if we remove the annotations completely. We do not actually maintain them. They would make sense if we move the tests in a separate repo.

2021-03-08 12:21 UTC, ekouts approved these changes

2021-03-08 18:09 UTC, vkarak approved these changes

2021-03-08 18:09 UTC, vkarak commented on cscs-checks/prgenv/mpi.py
> -                                    'PrgEnv-intel', 'PrgEnv-aocc']
Why did you remove `aocc`?

2021-03-08 18:18 UTC, teojgo commented on cscs-checks/prgenv/mpi.py
> -                                    'PrgEnv-intel', 'PrgEnv-aocc']
There is an incompatibility with libsci

2021-03-08 22:14 UTC, merged