[doc] Add modules = nomod to example configuration file
eth-cscs/reframe pull request #1890
Opened 2021-03-25 06:53 UTC by mabraham

A laptop would generally not have modules, so saying that explicitly
will help highlight to new users that a module setting can be
useful. There is a modules setting below for daint, but at least one
user skimmed over the more complex case.

The line numbers for the literal includes need to be bumped if they
are greater than 15, and a range including 15 is shown, then the
highlighting can need a bump. Note that the latter index within the
range shown, so don't always need a bump.

Fixes #1887

2021-03-25 07:21 UTC, mabraham commented
I'd proof-read this if I could. Is the build docs artifact online somewhere, or would have to build it myself?

2021-03-25 11:08 UTC, jjotero reviewed
I've got a bit of a different approach to state this in a clearer way. I'm not convinced that adding the `modules_system` option is the best way for this here, since this is an optional parameter and it already defaults to `nomod`. I feel that tutorials should be kept as light as possible.

What about just expanding on this in the `modules_system` bullet instead? (see the comment below)

2021-03-25 11:13 UTC, vkarak commented
I am also of the opinion to keep the tutorials as light as possible and this was the initial principle. I would go for a warning issued by `nomod` whenever a test tries a module operation. I just haven't had the time to open an issue for this. Let's see how this works and if it produces false noise, we might consider updating the documentation as proposed in this PR.

2021-03-25 12:42 UTC, mabraham commented on tutorials/config/settings.py
> +            'modules_system': 'nomod',
Yes, that is true, but a user of the tutorials typically doesn't know that. They probably don't even know that that setting up modules is a thing they might want to do (see #1887) but by being mildly redundant they might get the clue that if they want modules support then they need to set things up. 

If `util.find_modules` gave an error when `modules_system` was `nomod` then there'd have been a way to find out that my problem lay in configuration, and not in invalid construction of my test parameters.

The next example configuration on `daint` does have `modules_system`, but also a lot of partition complexity. When I read the docs, I knew I didn't need the latter for running on my dedicated node, so never saw that the example for modules_system was also mentioned there.

There is text lower down that mentions `modules_system` but it's a bit buried in a section about partitions, so again I missed it.

2021-03-25 12:42 UTC, mabraham commented on docs/configure.rst
>  Each system is associated with a set of properties, which in this case are the following:
Looks good

2021-04-12 16:29 UTC, vkarak commented on docs/configure.rst
>  Each system is associated with a set of properties, which in this case are the following:
@jjotero I will keep the original syntax, since these are only a subset of properties that a system partition can have.

2021-04-12 22:06 UTC, vkarak requested changes
I've done a PR with the necessary fixes to your branch: https://github.com/ENCCS/reframe/pull/1

2021-04-16 07:19 UTC, vkarak commented
Replaced by #1932

2021-04-16 07:19 UTC, closed without merging