[test] PGI workaround
eth-cscs/reframe pull request #1931
Opened 2021-04-15 13:01 UTC by ajocksch

This change introduces the workaround

-D__PGIC__=19

2021-04-15 14:19 UTC, kraushm approved these changes
lgtm.

2021-04-16 07:41 UTC, victorusu approved these changes
`lgtm`

2021-04-16 07:43 UTC, vkarak requested changes

2021-04-16 07:43 UTC, vkarak commented on cscs-checks/mch/gpu_direct_cuda_tsa_pgi_workaround.py
> +    def setflags(self):
As discussed offline, please add a meaningful name here and a meaningful PR title.

2021-04-16 08:12 UTC, vkarak commented on cscs-checks/mch/gpu_direct_cuda_tsa_pgi_workaround.py
> +    def setflags(self):
```suggestion
    def pgi_workaround_tsa(self):
```

2021-04-16 09:34 UTC, vkarak requested changes
Wait a sec, why do we need a new test for this?! Wouldn't just a hook to the existing one work?

2021-04-19 07:40 UTC, pep8speaks commented
Hello @ajocksch, Thank you for updating!

* In the file [`cscs-checks/mch/gpu_direct_cuda.py`](https://github.com/eth-cscs/reframe/blob/6efd4f317401e2c7cac679d84f75d68508dd9ee9/cscs-checks/mch/gpu_direct_cuda.py):

> [Line 40:5](https://github.com/eth-cscs/reframe/blob/6efd4f317401e2c7cac679d84f75d68508dd9ee9/cscs-checks/mch/gpu_direct_cuda.py#L40): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2021-04-20 11:30 UTC, vkarak approved these changes

2021-04-20 16:15 UTC, merged