[ci] remove collections for alps
eth-cscs/reframe pull request #1939
Opened 2021-04-20 13:32 UTC by jgphpc

Closes #1938

2021-04-20 15:54 UTC, teojgo requested changes
I think you can remove the `collection` completely.

2021-04-20 16:18 UTC, vkarak requested changes

2021-04-20 16:18 UTC, vkarak commented on config/cscs.py
> +                {'name': 'PrgEnv-aocc', 'collection': False}
There is no need for the extended syntax. Simply write it as `'modules': ['PrgEnv-aocc']` etc.

2021-04-21 10:38 UTC, teojgo approved these changes
lgtm

2021-04-21 11:26 UTC, jgphpc commented
When I run:
```
class XTest_new(rfm.CompileOnlyRegressionTest):
    m = parameter(['cray-mpich/8.1.4'])
```

I get:
```
  * Reason: key error: 'collection'
Traceback (most recent call last):
  File "/users/piccinal/reframe.git/reframe/frontend/executors/__init__.py", line 269, in _safe_call
    return fn(*args, **kwargs)
  File "/users/piccinal/reframe.git/reframe/core/hooks.py", line 36, in _fn
    func(obj, *args, **kwargs)
  File "/users/piccinal/reframe.git/reframe/core/pipeline.py", line 97, in _wrapped
    return fn(*args, **kwargs)
  File "/users/piccinal/reframe.git/reframe/core/pipeline.py", line 1250, in compile
    trap_errors=True
  File "/users/piccinal/reframe.git/reframe/core/schedulers/__init__.py", line 364, in prepare
    builder.write(runtime.emit_loadenv_commands(*environs))
  File "/users/piccinal/reframe.git/reframe/core/runtime.py", line 237, in emit_loadenv_commands
    _, commands = loadenv(*environs)
  File "/users/piccinal/reframe.git/reframe/core/runtime.py", line 224, in loadenv
    m, mod['collection'], mod['path'],
KeyError: 'collection'
```

2021-04-21 11:38 UTC, vkarak commented
> When I run:
> 
> ```
> class XTest_new(rfm.CompileOnlyRegressionTest):
>     m = parameter(['cray-mpich/8.1.4'])
> ```
> 
> I get:
> 
> ```
>   * Reason: key error: 'collection'
> Traceback (most recent call last):
>   File "/users/piccinal/reframe.git/reframe/frontend/executors/__init__.py", line 269, in _safe_call
>     return fn(*args, **kwargs)
>   File "/users/piccinal/reframe.git/reframe/core/hooks.py", line 36, in _fn
>     func(obj, *args, **kwargs)
>   File "/users/piccinal/reframe.git/reframe/core/pipeline.py", line 97, in _wrapped
>     return fn(*args, **kwargs)
>   File "/users/piccinal/reframe.git/reframe/core/pipeline.py", line 1250, in compile
>     trap_errors=True
>   File "/users/piccinal/reframe.git/reframe/core/schedulers/__init__.py", line 364, in prepare
>     builder.write(runtime.emit_loadenv_commands(*environs))
>   File "/users/piccinal/reframe.git/reframe/core/runtime.py", line 237, in emit_loadenv_commands
>     _, commands = loadenv(*environs)
>   File "/users/piccinal/reframe.git/reframe/core/runtime.py", line 224, in loadenv
>     m, mod['collection'], mod['path'],
> KeyError: 'collection'
> ```
> 
> > {'name': 'PrgEnv-gnu', 'collection': False} works around it

I think this is a bug. Can you open one?

The `'collection': False` is not the "right" workaround. You don't need to use dictionaries. Just define the the modules in the classic way:

```python
'modules': ['PrgEnv-gnu']
```

2021-04-22 10:05 UTC, jgphpc commented
https://github.com/eth-cscs/reframe/issues/1943

2021-04-22 11:51 UTC, vkarak approved these changes

2021-04-22 11:52 UTC, merged