[bugfix] Print a warning when search path files don't exist
eth-cscs/reframe pull request #1949
Opened 2021-04-26 11:50 UTC by ekouts

Fixes #1928.

2021-04-26 14:28 UTC, vkarak requested changes
I think the warning should be issued by the `load_all()` function of the loader:

https://github.com/eth-cscs/reframe/blob/23dc03bd2b85adcae62fb69be51a047e5cef1be5/reframe/frontend/loader.py#L205-L206

2021-04-26 14:34 UTC, teojgo commented
I agree with @vkarak, this way you will also take into account the case where the checkpath is given by the env variable.

2021-04-26 14:53 UTC, ekouts commented
> I think the warning should be issued by the `load_all()` function of the loader:
> 
> https://github.com/eth-cscs/reframe/blob/23dc03bd2b85adcae62fb69be51a047e5cef1be5/reframe/frontend/loader.py#L205-L206

@vkarak  @teojgo  What about the case that the user doesn't pass any path? Should the warning appear when he passes nothing and there is no `${RFM_INSTALL_PREFIX}/checks/`? That's why I made the check earlier.

2021-04-26 14:58 UTC, vkarak commented
@ekouts I think the `load_all()` will cover that case, too. `load_all()` is always called to load the tests.

2021-04-26 15:01 UTC, ekouts commented
Ok, then I will change it. I thought we don't want a warning in that case.

2021-04-26 15:03 UTC, vkarak commented
We do want a warning there, too.

2021-04-27 13:19 UTC, teojgo approved these changes

2021-04-27 19:00 UTC, vkarak commented on reframe/frontend/loader.py
> +                getlogger().warning(f"check path {d!r} doesn't exist")
Do not use abbreviated forms in error messages. I will fix this and merge it.

```suggestion
                getlogger().warning(f'check path {d!r} does not exist')
```

2021-04-27 19:14 UTC, vkarak approved these changes

2021-04-27 19:26 UTC, merged