[feat] Add HTTPJSONHandler logging handler
eth-cscs/reframe pull request #1964
Opened 2021-05-06 15:44 UTC by teojgo

Fixes #1962

2021-05-06 15:44 UTC, pep8speaks commented
Hello @teojgo, Thank you for submitting the Pull Request!



* In the file [`reframe/core/logging.py`](https://github.com/eth-cscs/reframe/blob/78111a6b1f4169b435c83e7416ff1655c98f96db/reframe/core/logging.py):

> [Line 340:1](https://github.com/eth-cscs/reframe/blob/78111a6b1f4169b435c83e7416ff1655c98f96db/reframe/core/logging.py#L340): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 352:5](https://github.com/eth-cscs/reframe/blob/78111a6b1f4169b435c83e7416ff1655c98f96db/reframe/core/logging.py#L352): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 389:14](https://github.com/eth-cscs/reframe/blob/78111a6b1f4169b435c83e7416ff1655c98f96db/reframe/core/logging.py#L389): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 394:18](https://github.com/eth-cscs/reframe/blob/78111a6b1f4169b435c83e7416ff1655c98f96db/reframe/core/logging.py#L394): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'



Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2021-05-06 15:45 UTC, teojgo commented
I need also to update the documentation

2021-05-08 19:03 UTC, vkarak requested changes

2021-05-08 19:03 UTC, vkarak commented on reframe/frontend/cli.py
> +    )
I think we should a URI to encompass everything.

2021-05-10 18:31 UTC, vkarak requested changes

2021-05-10 18:31 UTC, vkarak commented on docs/config_reference.rst
> +   The uri to be used in the http(s) request server defined as ``http(s)://host:port/url``.
```suggestion
   The URI to be used in the HTTP(S) request server defined as ``schema://host:port/path``.
```

2021-05-10 18:31 UTC, vkarak commented on docs/config_reference.rst
> +This log handler uses internally `requests <https://pypi.org/project/requests/>`__.
I don't think that this information is useful for the user documentation.

2021-05-10 18:31 UTC, vkarak commented on docs/config_reference.rst
> +The ``httpjson`` handler sends log messages in JSON format using an HTTP POST request to the specified uri.
```suggestion
The ``httpjson`` handler sends log messages in JSON format using an HTTP POST request to the specified URI.
```

2021-05-10 18:31 UTC, vkarak commented on docs/config_reference.rst
> +Although the ``format`` is defined for this handler, it is not only the log message that will be transmitted.
Do we need to set the `format`?

2021-05-12 09:35 UTC, merged