[feat] Support test retries in the JUnit report
eth-cscs/reframe pull request #1965
Opened 2021-05-07 15:19 UTC by teojgo

* Each retry(run) is passed as an individual testsuite to the junit report.

Fixes #1963

2021-05-07 21:58 UTC, vkarak approved these changes
Lgtm. Do you have an example of how it shows up on Gitlab and Jenkins?

2021-05-07 22:02 UTC, vkarak requested changes

2021-05-07 22:02 UTC, vkarak commented on reframe/frontend/runreport.py
> +                'name': f'ReFrame run {run_id + 1}',
```suggestion
                'name': f'ReFrame run {run_id}',
```

2021-05-07 22:13 UTC, vkarak approved these changes

2021-05-09 20:22 UTC, vkarak requested changes
We need also to remove the sentence in the documentation stating that this option does not work with the retries.

2021-05-10 08:47 UTC, jgphpc commented
> Lgtm. Do you have an example of how it shows up on Gitlab and Jenkins?

see https://git.cscs.ch/c4k/c4kcust/example-junit/-/pipelines/26043/test_report

2021-05-10 08:57 UTC, jgphpc commented
> Have you ran with the `--retries=<number>` option?

see https://git.cscs.ch/c4k/c4kcust/example-junit/-/pipelines/26045/test_report

2021-05-10 11:08 UTC, vkarak commented
Thanks @jgphpc. It seems that Gitlab combines the results of everything. Anyway, it's up to each program how interprets the results, at least we encode everything.

2021-05-10 12:19 UTC, teojgo commented
> Thanks @jgphpc. It seems that Gitlab combines the results of everything. Anyway, it's up to each program how interprets the results, at least we encode everything.

I could append a `run{id}` to the name of each test to differentiate.

2021-05-10 18:23 UTC, vkarak commented
@jenkins-cscs retry daint dom

2021-05-10 18:24 UTC, vkarak commented
> I could append a run{id} to the name of each test to differentiate.

No, that would mess with the actual test naming.

2021-05-10 18:37 UTC, vkarak approved these changes

2021-05-10 18:38 UTC, merged