[feat] Add rerun to the failure statistics
eth-cscs/reframe pull request #2016
Opened 2021-06-16 10:55 UTC by jgphpc

Closes https://github.com/eth-cscs/reframe/issues/1947

2021-06-16 10:55 UTC, pep8speaks commented
Hello @jgphpc, Thank you for submitting the Pull Request!

* In the file [`reframe/frontend/statistics.py`](https://github.com/eth-cscs/reframe/blob/a6e424199749a62fbbbd3dfd47fdfff7eae0853f/reframe/frontend/statistics.py):

> [Line 292:80](https://github.com/eth-cscs/reframe/blob/a6e424199749a62fbbbd3dfd47fdfff7eae0853f/reframe/frontend/statistics.py#L292): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 292:100](https://github.com/eth-cscs/reframe/blob/a6e424199749a62fbbbd3dfd47fdfff7eae0853f/reframe/frontend/statistics.py#L292): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2021-06-23 09:39 UTC, ekouts requested changes
I am not sure this was what @victorusu originally asked for in issue #1947. Victor maybe you can shed some light:
1. I think he meant to print something like this
`Rerun the failed tests using '--restore-session <report-file> -n <name1> -p <partition1> --system <system> -n <name2> -p <partition2>  ...'`. Or we can make it simpler with 
`Rerun the failed tests using '--restore-session --failed -r'`.
2. I don't agree to print it only in the failure statistic, when we pass `--failure-stats`. This is not really part of the statistics and I prefer that we print it always. What do you guys think?

2021-06-23 09:39 UTC, ekouts commented on reframe/frontend/statistics.py
> +            stats_body.append(stats_hline)
I am not sure whether we want a `stats_hline` here or a solid line. The result now is:
```
==============================================================================
FAILURE STATISTICS

Total number of test cases: 10
Total number of failures: 4

Phase         #     Failing test cases
------------- ----- ------------------------------------------------------------
sanity        1     [T2, builtin, generic:default]
startup       2     [T7, None, None]
                    [T9, None, None]
setup         1     [T8, builtin, generic:default]
------------- ----- ------------------------------------------------------------
Rerun the failed tests with:
 -n T2 -p builtin --system generic:default -r
------------- ----- ------------------------------------------------------------
Rerun the failed tests with:
 -n T7 -p None --system None -r
 -n T9 -p None --system None -r
------------- ----- ------------------------------------------------------------
Rerun the failed tests with:
 -n T8 -p builtin --system generic:default -r
------------------------------------------------------------------------------
```

2021-07-13 21:14 UTC, vkarak requested changes
I agree with @ekouts. I don't think that this is what @victorusu requested in the corresponding issue. I interpret it as a simple line at the vey end (after the failure statistics) saying the something like "Rerun all failed tests with `reframe --restore-session=report-file --failed`. I personally also thing that the `report-file` is not needed. But @victorusu, please explain more what's your feature request is about.

2021-07-14 20:46 UTC, victorusu approved these changes
`lgtm`

2021-07-14 20:46 UTC, vkarak commented
I updated this PR to print the report file always at the end of the session. I am against adding a `Rerun with` type of message, cos it introduces unnecessary complexity to the implementation. We report the file here, and somebody can use it with the `--restore-session` option.

2021-07-14 20:47 UTC, vkarak approved these changes

2021-07-14 21:03 UTC, merged