dom
eth-cscs/reframe pull request #2029
Opened 2021-06-24 09:48 UTC by ajocksch

halo_cell_exchange check PrgEnv-nvidia

2021-06-24 10:05 UTC, jgphpc approved these changes

2021-06-24 10:23 UTC, jjotero commented
@jgphpc There are heaps of failures for this test. At least, the performance references should be adjusted to a less optimistic value.

2021-06-28 06:19 UTC, jgphpc requested changes
I get the same failure (in performance) with almost all PrgEnv.
Can we relax the performance limits or is there an issue ?

2021-07-01 10:02 UTC, jjotero commented
@jgphpc I don't think there is any performance issue. I just think that the tolerances are way too strict for this case. I also vote for relaxing them.

2021-07-05 07:53 UTC, jjotero requested changes

2021-07-05 07:53 UTC, jjotero commented on cscs-checks/mch/collectives_halo.py
> +        self.strict_check = False
I think you've added the `strict_check` into the wrong test. This should go into the `halo_cell_exchange.py` instead.

2021-07-05 15:09 UTC, jgphpc approved these changes

2021-07-06 09:47 UTC, jjotero approved these changes

2021-07-06 10:36 UTC, merged