[test] Update automatic_arrays_acc
eth-cscs/reframe pull request #2034
Opened 2021-06-24 12:27 UTC by ajocksch

2021-06-25 14:06 UTC, teojgo requested changes

2021-06-25 14:06 UTC, teojgo commented on cscs-checks/mch/automatic_arrays_acc.py
> +            if (not self.current_environ.name.startswith('PrgEnv-nvidia')):
The outer parentheses are not needed.

2021-06-25 14:06 UTC, teojgo commented on cscs-checks/mch/automatic_arrays_acc.py
>      def __init__(self):
Can you also adapt so that this uses class level attrributes instead of the older `__init__` method?

2021-06-28 07:17 UTC, jjotero approved these changes
lgtm

2021-06-28 12:50 UTC, jjotero commented
@jenkins-cscs retry tsa

2021-06-28 14:04 UTC, jjotero commented
@jenkins-cscs retry daint

2021-06-28 14:57 UTC, merged