[test] Update hello, world tests
eth-cscs/reframe pull request #2075
Opened 2021-07-15 12:34 UTC by victorusu

2021-07-15 12:34 UTC, pep8speaks commented
Hello @victorusu, Thank you for submitting the Pull Request!

* In the file [`cscs-checks/prgenv/helloworld.py`](https://github.com/eth-cscs/reframe/blob/342f26621de0874afcf59053e34e669fd3a6ba21/cscs-checks/prgenv/helloworld.py):

> [Line 71:80](https://github.com/eth-cscs/reframe/blob/342f26621de0874afcf59053e34e669fd3a6ba21/cscs-checks/prgenv/helloworld.py#L71): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 105:9](https://github.com/eth-cscs/reframe/blob/342f26621de0874afcf59053e34e669fd3a6ba21/cscs-checks/prgenv/helloworld.py#L105): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 137:41](https://github.com/eth-cscs/reframe/blob/342f26621de0874afcf59053e34e669fd3a6ba21/cscs-checks/prgenv/helloworld.py#L137): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 138:41](https://github.com/eth-cscs/reframe/blob/342f26621de0874afcf59053e34e669fd3a6ba21/cscs-checks/prgenv/helloworld.py#L138): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 139:41](https://github.com/eth-cscs/reframe/blob/342f26621de0874afcf59053e34e669fd3a6ba21/cscs-checks/prgenv/helloworld.py#L139): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2021-07-15 12:42 UTC, teojgo requested changes

2021-07-15 12:42 UTC, teojgo commented on cscs-checks/prgenv/helloworld.py
> +                                        'PrgEnv-pgi-nompi-nocuda',
Align this, one space in.

2021-07-15 12:42 UTC, teojgo commented on cscs-checks/prgenv/helloworld.py
> +    def set_sanity_patterns(self):
Use the `@sanity_pattern` decorator here directly.

2021-07-15 17:04 UTC, victorusu commented
@jenkins-cscs retry all

2021-07-16 08:13 UTC, jjotero reviewed
My comments are only related to the actual stages where hooks should be attached to. I think that as a general rule (we should probably have a rationale doc covering this) whichever test attribute cannot be set directly in the class body, should be placed in a hook that executes just in time for what the hook should do. Otherwise we might end up with loads of `@run_after('init')` hooks, which kind of defeats the purpose of having hooks to begin with. It also gets a bit hard to see which of those hooks are actually needed after init, and which others could actually execute at a later stage.

2021-07-16 08:13 UTC, jjotero commented on cscs-checks/prgenv/helloworld.py
> +    @run_after('init')
I think we could try and get the hooks in pipeline-order when possible.
```suggestion
    @run_before('performance')
```

2021-07-16 08:13 UTC, jjotero commented on cscs-checks/prgenv/helloworld.py
> +    @run_after('init')
```suggestion
    @run_before('run')
```

2021-07-16 08:13 UTC, jjotero commented on cscs-checks/prgenv/helloworld.py
> +    @run_after('init')
```suggestion
    @run_before('compile')
```

2021-07-16 08:13 UTC, jjotero commented on cscs-checks/prgenv/helloworld.py
> +    @run_after('init')
```suggestion
    @run_before('compile')
```

2021-07-16 08:13 UTC, jjotero commented on cscs-checks/prgenv/helloworld.py
> +    @run_after('init')
```suggestion
    @run_before('compile')
```

2021-07-16 08:13 UTC, jjotero commented on cscs-checks/prgenv/helloworld.py
> +    @run_after('init')
```suggestion
    @run_before('compile')
```

2021-07-16 08:13 UTC, jjotero commented on cscs-checks/prgenv/helloworld.py
> +    @run_after('init')
```suggestion
    @run_before('run')
```

2021-07-26 09:27 UTC, teojgo commented
I will address the PR comments on this.

2021-07-26 11:12 UTC, jjotero approved these changes

2021-08-04 16:42 UTC, vkarak requested changes

2021-08-04 16:42 UTC, vkarak commented on cscs-checks/prgenv/helloworld.py
> +    compilation_time_seconds = None
Shouldn't that be a variable and not a class variable? Each test is setting that.

2021-08-04 16:42 UTC, vkarak commented on cscs-checks/prgenv/helloworld.py
> +    }
This is very local to the `set_description` hook, so I'd move it there.

2021-08-04 16:42 UTC, vkarak commented on cscs-checks/prgenv/helloworld.py
> +    def add_dynamic_only_systems(self):
```suggestion
    def adapt_valid_systems(self):
```

2021-08-04 16:42 UTC, vkarak commented on cscs-checks/prgenv/helloworld.py
> +    def set_craylinktype_env_variable(self):
```suggestion
    def setup_linking_type(self):
```

2021-08-04 16:42 UTC, vkarak commented on cscs-checks/prgenv/helloworld.py
> +    def set_sanity_patterns(self):
```suggestion
    def assert_hello_world(self):
```

2021-08-04 16:42 UTC, vkarak commented on cscs-checks/prgenv/helloworld.py
> +    def set_performance_patterns(self):
```suggestion
    def capture_build_time(self):
```

2021-08-04 16:42 UTC, vkarak commented on cscs-checks/prgenv/helloworld.py
>      def setflags(self):
I'd suggest something like this and you could merge it with the other hook setting the linking type.

```suggestion
    def prepare_build(self):
```

2021-08-04 16:42 UTC, vkarak commented on cscs-checks/prgenv/helloworld.py
> +        self.sourcepath += '_serial.' + self.lang
```suggestion
        self.sourcepath += f'_serial.{self.lang}'
```

2021-08-06 10:08 UTC, vkarak approved these changes
lgtm

2021-08-06 11:01 UTC, teojgo approved these changes

2021-08-06 11:03 UTC, merged