[test] Update IOR checks
eth-cscs/reframe pull request #2076
Opened 2021-07-15 12:34 UTC by victorusu

2021-07-15 17:04 UTC, victorusu commented
@jenkins-cscs retry all

2021-07-20 14:47 UTC, teojgo approved these changes

2021-07-20 21:46 UTC, vkarak requested changes

2021-07-20 21:46 UTC, vkarak commented on cscs-checks/system/io/ior_check.py
> +
No newline here.

2021-07-20 21:46 UTC, vkarak commented on cscs-checks/system/io/ior_check.py
> +    def extend_tags_based_on_fs(self):
```suggestion
    def add_fs_tags(self):
```

2021-07-20 21:46 UTC, vkarak commented on cscs-checks/system/io/ior_check.py
> +    def set_build_systems(self):
```suggestion
    @run_before('compile')
    def prepare_build(self):
```

If you prefer to have everything as a post-init hook, I'm fine.

2021-07-20 21:46 UTC, vkarak commented on cscs-checks/system/io/ior_check.py
>      def set_exec_opts(self):
I would combine this with the above hook in something called `prepare_run`.

2021-07-20 21:46 UTC, vkarak commented on cscs-checks/system/io/ior_check.py
> +        self.prerun_cmds = ['mkdir -p ' + self.test_dir]
```suggestion
        self.prerun_cmds = [f'mkdir -p {self.test_dir}']
```

2021-07-20 21:46 UTC, vkarak commented on cscs-checks/system/io/ior_check.py
> +    def set_sanity_perf_patterns(self):
I would split that and use the `@sanity_function` syntax for the sanity patterns.

2021-07-20 21:46 UTC, vkarak commented on cscs-checks/system/io/ior_check.py
> +    def set_sanity_perf_patterns(self):
See my comment above.

2021-07-22 09:43 UTC, vkarak commented
I am fixing this PR

2021-07-22 09:59 UTC, vkarak approved these changes

2021-07-22 19:42 UTC, merged