[feat] Remove deprecated features for 4.x
eth-cscs/reframe pull request #2096
Opened 2021-07-23 20:21 UTC by vkarak

Closes #1917.
Closes #1918.
Closes #2017.

2021-07-24 14:16 UTC, jjotero reviewed
Just a minor comment

2021-07-24 14:16 UTC, jjotero commented on reframe/core/pipeline.py
> +           Passing an integer to the ``how`` argument is no more supported.
no longer supported?

2021-07-26 05:42 UTC, ekouts requested changes
1. There are some references to `rfm.run_after` in `reframe/core/launchers`,  `reframe/core/schedulers/__init__.py` and `reframe/utility/__init__.py` that still need to be changed. They are part of documentation.
2. I see a lot of tests using the `parameterized_test` decorator in the branch. These should be fixed in a different PR, right?
3. There are also many tests using the `@sn.sanity_function` decorator in the branch. Different PR as well?

2021-07-26 09:06 UTC, jjotero approved these changes

2021-07-26 09:16 UTC, teojgo approved these changes

2021-07-26 19:10 UTC, vkarak commented
@ekouts I will fix (1). I guess that by saying "tests," you mean ReFrame tests, not unit tests. These should be fixed in different PRs.

2021-07-27 06:31 UTC, ekouts approved these changes
lgtm

2021-07-27 11:40 UTC, merged