[bugfix] Fix default `executable` assignment
eth-cscs/reframe pull request #2107
Opened 2021-08-02 13:11 UTC by jjotero

`RunOnlyRegressionTest` classes must be able to set the `executable` variable as `required`. However, this variable was set a default value during class instantiation. This assignment has now been moved into the `compile` stage.

closes #2106

2021-08-02 14:07 UTC, teojgo requested changes
Since the executable is required now, you should add an executable here: https://github.com/eth-cscs/reframe/blob/8a9ceeda69619d367820d5297f5018183d52a897/unittests/test_policies.py#L139 and maybe also the resources for the unittests.

2021-08-02 14:32 UTC, teojgo commented
@jjotero @vkarak Do you think that we should also mention that the `executable` is required for the `RunOnlyRegressionTest` in the tutorial?

2021-08-02 14:47 UTC, jjotero commented
@teojgo I think it could add that in the regression test API docs instead. Like a version changed box or something like that.

2021-08-03 21:39 UTC, vkarak requested changes
@jjotero @teojgo I think that a small note in the tutorial to alert the readers would be good.

2021-08-03 21:39 UTC, vkarak commented on reframe/core/pipeline.py
> +    #: .. versionchanged:: 3.8
```suggestion
    #: .. versionchanged:: 3.7.3
```

2021-08-06 11:08 UTC, teojgo approved these changes

2021-08-06 11:42 UTC, vkarak approved these changes
Lgtm now. I've done a minor rephrase in the docs.

2021-08-06 12:04 UTC, merged

2022-11-03 15:34 UTC, ireed commented
Is there a way to use two self.executable values in a single test? For example, if i want to run two different programs, how can i do something like _self.executable1='prog1'_, _self.executable2='prog2'_ with both appearing in the same submission script? This is to avoid a hack such as _self.executable='prog1\nsrun prog2'_, which i do quite often, but is not portable.

2022-11-03 15:46 UTC, teojgo commented
> Is there a way to use two self.executable values in a single test? For example, if i want to run two different programs, how can i do something like _self.executable1='prog1'_, _self.executable2='prog2'_ with both appearing in the same submission script? This is to avoid a hack such as _self.executable='prog1\nsrun prog2'_, which i do quite often, but is not portable.

If you want to run to executables with the same srun options then you can put the executable commands inside a bash script `run.sh` and then set the executable as `'run.sh'`.

2022-11-03 20:25 UTC, vkarak commented
@ireed You may also have a look on how to create scripts with multiple parallel launcher commands: https://reframe-hpc.readthedocs.io/en/stable/tutorial_advanced.html#adding-more-parallel-launch-commands