[feat] Add image name and verbosity level in CI script
eth-cscs/reframe pull request #2137
Opened 2021-08-18 12:34 UTC by mahendrapaipuri

- This PR emits docker image name, if defined in the parent CI script, in the generated CI scripts. 
- If the user chose to increase the verbosity in the parent CI script, the child scripts will also inherit the same level of verbosity. In the current implementation, there is no verbosity and it is hard for the user to debug the test failures. 
- Tested on simple [CI pipeline](https://gitlab.com/ska-telescope/sdp/ska-sdp-benchmark-tests/-/jobs/1513187407#L216).

Fixes #2134

2021-08-18 12:39 UTC, teojgo commented
Ok to test

2021-08-18 17:07 UTC, mahendrapaipuri commented
Does it sound logical to add a new configuration section for CI pipelines to define parameters like `before-script`, `after-script`, `expire_in` (for artifacts) so that they will be emitted in the generated `yaml` files?

2021-09-09 21:01 UTC, vkarak requested changes
@mahendrapaipuri thanks a lot for your PR! I have just a couple of minor comments. Also we should probably document these additions somewhere in the user documentation.

2021-09-10 08:48 UTC, mahendrapaipuri commented on reframe/frontend/ci.py
> +            'image': image_name,
Well, I did a test and it looks like placement of `image` keyword is indeed not critical. Changed to your suggestion.

2021-09-10 08:51 UTC, mahendrapaipuri commented on reframe/frontend/ci.py
> +    verbosity = 'v' * int(config.get('general/0/verbose'))
Cheers. Changed it too.

2021-09-10 20:29 UTC, vkarak approved these changes

2021-09-14 06:59 UTC, merged