[test] Modernize PETSC test
eth-cscs/reframe pull request #2142
Opened 2021-08-20 15:03 UTC by teojgo

2021-08-20 15:17 UTC, kraushm approved these changes
lgtm.

2021-08-23 09:40 UTC, vkarak requested changes

2021-08-23 09:40 UTC, vkarak commented on cscs-checks/libraries/petsc/petsc_helloworld.py
> +    def prg_intel_workaround(self):
```suggestion
    def intel_workaround(self):
```

2021-08-23 09:40 UTC, vkarak commented on cscs-checks/libraries/petsc/petsc_helloworld.py
> +    @run_after('setup')
I would put that in a pre-compile hook.

2021-08-23 09:49 UTC, vkarak approved these changes

2021-08-23 11:58 UTC, teojgo commented
@jenkins-cscs retry daint

2021-08-23 21:06 UTC, merged