[test] Modernize GREASY Tests
eth-cscs/reframe pull request #2144
Opened 2021-08-23 13:41 UTC by teojgo

2021-08-23 14:49 UTC, jjotero requested changes

2021-08-23 14:49 UTC, jjotero commented on cscs-checks/apps/greasy/greasy_check.py
> +    greasy_logfile = 'greasy.log'
```suggestion
    tasks_file = variable(str, value='tasks.txt')
    greasy_logfile = variable(str, 'greasy.log')
```

2021-08-23 14:49 UTC, jjotero commented on cscs-checks/apps/greasy/greasy_check.py
> +    nnodes = 2
```suggestion
    nnodes = variable(int, value=2)
```

2021-08-23 14:49 UTC, jjotero commented on cscs-checks/apps/greasy/greasy_check.py
> +    sleep_time = 60
```suggestion
    sleep_time = variable(int, value=60)
```

2021-08-23 14:49 UTC, jjotero commented on cscs-checks/apps/greasy/greasy_check.py
> +        self.ranks_per_worker, self.cpus_per_worker = self.configuration[4:6]
I'd probably also create typed variables for all these so you get type-checking on the parameters.

2021-08-23 14:49 UTC, jjotero commented on cscs-checks/apps/greasy/greasy_check.py
> +    def set_variables(self):
```suggestion
    def set_environment_variables(self):
```

2021-08-23 14:49 UTC, jjotero commented on cscs-checks/apps/greasy/greasy_check.py
> +            if self.configuration.variant != 'serial':
```suggestion
            if 'serial' not in self.variant:
```

2021-08-23 15:37 UTC, jjotero approved these changes
lgtm

2021-08-24 09:11 UTC, vkarak commented on cscs-checks/apps/greasy/greasy_check.py
> +    def set_perf_patterns(self):
What about using the new `@performance_function` decorator that was just merged?

2021-08-24 10:03 UTC, vkarak approved these changes

2021-08-24 11:38 UTC, merged