[test] Modernize strided bandwidth test
eth-cscs/reframe pull request #2159
Opened 2021-08-27 12:21 UTC by rsarm

2021-08-27 15:53 UTC, teojgo submitted a review, later dismissed

2021-08-28 21:15 UTC, vkarak requested changes

2021-08-28 21:15 UTC, vkarak commented on cscs-checks/microbenchmarks/cpu/strided_bandwidth/strides.py
> +    }
This is not needed now. You can query this from the `self.current_partition.processor`. And if now processor configuration is found (i.e., the remote auto-detection has not run, you should skip the test).

2021-08-28 21:15 UTC, vkarak commented on cscs-checks/microbenchmarks/cpu/strided_bandwidth/strides.py
>          return self.job.num_tasks
Is this really needed now? The test is not flexible afaics.

2021-09-10 21:54 UTC, vkarak approved these changes
I have updated the test and made it (a) parametrised and (b) system agnostic by using the autodetected processor info. The reference values are set based on the processor architecture.

2021-09-13 07:18 UTC, merged