[testlib] Add a generic test for TensorFlow with Horovod
eth-cscs/reframe pull request #2182
Opened 2021-09-09 14:48 UTC by hurricane642

This is a continuation of the work on the test library. This PR work has been done with Tensorflow tests. A new file base_check.py has been added, introducing the main class for the Tensorflow test, as well as the CSCS tests inherited from it.

2021-09-09 14:48 UTC, pep8speaks commented
Hello @hurricane642, Thank you for submitting the Pull Request!



* In the file [`hpctestlib/apps/tensorflow/base_check.py`](https://github.com/eth-cscs/reframe/blob/5ea45fd00b28d322153f7bfe7d8033fd8a764198/hpctestlib/apps/tensorflow/base_check.py):

> [Line 66:20](https://github.com/eth-cscs/reframe/blob/5ea45fd00b28d322153f7bfe7d8033fd8a764198/hpctestlib/apps/tensorflow/base_check.py#L66): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 72:20](https://github.com/eth-cscs/reframe/blob/5ea45fd00b28d322153f7bfe7d8033fd8a764198/hpctestlib/apps/tensorflow/base_check.py#L72): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent

Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2021-09-10 09:22 UTC, teojgo commented
Ok to test

2021-09-13 11:41 UTC, victorusu commented
@jenkins-cscs retry all

2021-09-15 11:20 UTC, rsarm approved these changes

2021-11-15 17:54 UTC, vkarak requested changes
It needs work to be ready to be merged this one.

2021-11-16 17:28 UTC, vkarak approved these changes

2021-11-16 20:46 UTC, merged