[test] Add generic Paraview check for the cscs-supported apps into hpctestlib/apps
eth-cscs/reframe pull request #2185
Opened 2021-09-09 15:40 UTC by hurricane642

This is a continuation of the work on the test library. This PR work has been done with Paraview tests. A new file base_check.py has been added, introducing the main class for the Paraview test, as well as the CSCS tests inherited from it.

2021-09-10 09:19 UTC, teojgo commented
Ok to test

2021-09-10 13:30 UTC, teojgo requested changes
Just remove the unused imports.

2021-09-10 13:51 UTC, teojgo requested changes

2021-09-10 13:51 UTC, teojgo commented on cscs-checks/apps/paraview/paraview_check.py
> +from hpctestlib.apps.paraview.base_check import ParaView_BaseCheck
Add also a blank line before this.

2021-09-10 14:02 UTC, teojgo requested changes

2021-09-10 14:02 UTC, teojgo commented on hpctestlib/apps/paraview/base_check.py
> +    def set_sanity(self):
Can you change and use the `@sanify_function` here?

2021-09-10 14:13 UTC, teojgo approved these changes

2021-11-30 15:56 UTC, vkarak commented
This still needs substantial work, so I'm closing the PR due to time constraints. It will be added to the library at a later time.

2021-11-30 15:56 UTC, closed without merging