[test] Modernize hpcg test
eth-cscs/reframe pull request #2203
Opened 2021-09-27 11:54 UTC by ekouts

2021-09-27 14:16 UTC, teojgo requested changes

2021-09-27 14:16 UTC, teojgo commented on cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
> +        num_nodes = self.num_tasks_assigned / self.num_tasks_per_node
```suggestion
        num_nodes = self.num_tasks_assigned // self.num_tasks_per_node
```

2021-09-27 14:16 UTC, teojgo commented on cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
>          num_nodes = self.num_tasks_assigned / self.num_tasks_per_node
```suggestion
        num_nodes = self.num_tasks_assigned // self.num_tasks_per_node
```

2021-09-27 14:16 UTC, teojgo commented on cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py
> +        'daint:mc':  36,
You can query these via the `self.current_partition.processor.num_cores`

2021-09-27 15:02 UTC, pep8speaks commented
Hello @ekouts, Thank you for updating!

* In the file [`cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py`](https://github.com/eth-cscs/reframe/blob/0f068c7b2f40a7d19a486764363b99739d930661/cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py):

> [Line 109:13](https://github.com/eth-cscs/reframe/blob/0f068c7b2f40a7d19a486764363b99739d930661/cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py#L109): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 110:13](https://github.com/eth-cscs/reframe/blob/0f068c7b2f40a7d19a486764363b99739d930661/cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py#L110): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 111:13](https://github.com/eth-cscs/reframe/blob/0f068c7b2f40a7d19a486764363b99739d930661/cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py#L111): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 197:13](https://github.com/eth-cscs/reframe/blob/0f068c7b2f40a7d19a486764363b99739d930661/cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py#L197): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 198:13](https://github.com/eth-cscs/reframe/blob/0f068c7b2f40a7d19a486764363b99739d930661/cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py#L198): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 199:13](https://github.com/eth-cscs/reframe/blob/0f068c7b2f40a7d19a486764363b99739d930661/cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py#L199): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 280:13](https://github.com/eth-cscs/reframe/blob/0f068c7b2f40a7d19a486764363b99739d930661/cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py#L280): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 281:13](https://github.com/eth-cscs/reframe/blob/0f068c7b2f40a7d19a486764363b99739d930661/cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py#L281): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 282:13](https://github.com/eth-cscs/reframe/blob/0f068c7b2f40a7d19a486764363b99739d930661/cscs-checks/microbenchmarks/hpcg/hpcg_benchmark.py#L282): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented

Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2021-11-09 22:04 UTC, vkarak approved these changes

2021-11-12 23:15 UTC, merged