[feat] Add a utility function to skip tests that have no topology information
eth-cscs/reframe pull request #2267
Opened 2021-11-13 20:09 UTC by vkarak

This is quite useful with the topology autodetection, since it should be called the the first time that the topology is requested in a test. Otherwise, users would have to write a post-setup hook doing the same thing.

2021-11-13 20:09 UTC, pep8speaks commented
Hello @vkarak, Thank you for submitting the Pull Request!

* In the file [`reframe/core/pipeline.py`](https://github.com/eth-cscs/reframe/blob/eacef7fe3643afab7a419ffdbc7929f2c3d00014/reframe/core/pipeline.py):

> [Line 2219:10](https://github.com/eth-cscs/reframe/blob/eacef7fe3643afab7a419ffdbc7929f2c3d00014/reframe/core/pipeline.py#L2219): [E901](https://duckduckgo.com/?q=pep8%20E901) IndentationError: unindent does not match any outer indentation level

Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2021-11-15 16:34 UTC, teojgo requested changes

2021-11-15 16:34 UTC, teojgo commented on reframe/core/pipeline.py
> +                     f'no topology information found for partition {pname!r}')
```suggestion
                     msg or f'no topology information found for partition {pname!r}')
```

2021-11-16 08:14 UTC, teojgo approved these changes

2021-11-16 09:19 UTC, ekouts approved these changes

2021-11-16 09:20 UTC, merged