[bugfix] Update paraview_check for new release (5.9 and 5.10) and for new Mesa libraries
eth-cscs/reframe pull request #2286
Opened 2021-11-24 11:24 UTC by jfavre

I removed the check on Vendor because it is redundant anyway with the check for llvmpipe

2021-11-24 11:28 UTC, pep8speaks commented
Hello @jfavre, Thank you for updating!



* In the file [`cscs-checks/apps/paraview/src/coloredSphere.py`](https://github.com/eth-cscs/reframe/blob/b8a246aa4e34a74a17f10d3e9a58cf841752dc11/cscs-checks/apps/paraview/src/coloredSphere.py):

> [Line 9:8](https://github.com/eth-cscs/reframe/blob/b8a246aa4e34a74a17f10d3e9a58cf841752dc11/cscs-checks/apps/paraview/src/coloredSphere.py#L9): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 9:80](https://github.com/eth-cscs/reframe/blob/b8a246aa4e34a74a17f10d3e9a58cf841752dc11/cscs-checks/apps/paraview/src/coloredSphere.py#L9): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (125 > 79 characters)
> [Line 10:1](https://github.com/eth-cscs/reframe/blob/b8a246aa4e34a74a17f10d3e9a58cf841752dc11/cscs-checks/apps/paraview/src/coloredSphere.py#L10): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 11:1](https://github.com/eth-cscs/reframe/blob/b8a246aa4e34a74a17f10d3e9a58cf841752dc11/cscs-checks/apps/paraview/src/coloredSphere.py#L11): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 11:80](https://github.com/eth-cscs/reframe/blob/b8a246aa4e34a74a17f10d3e9a58cf841752dc11/cscs-checks/apps/paraview/src/coloredSphere.py#L11): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (107 > 79 characters)
> [Line 28:80](https://github.com/eth-cscs/reframe/blob/b8a246aa4e34a74a17f10d3e9a58cf841752dc11/cscs-checks/apps/paraview/src/coloredSphere.py#L28): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 30:80](https://github.com/eth-cscs/reframe/blob/b8a246aa4e34a74a17f10d3e9a58cf841752dc11/cscs-checks/apps/paraview/src/coloredSphere.py#L30): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)

Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2021-11-24 11:44 UTC, jfavre commented
addresses https://jira.cscs.ch/browse/AVAILAPPS-12

2021-12-03 12:20 UTC, vkarak approved these changes

2021-12-03 15:45 UTC, vkarak commented
@jfavre The test fails on Eiger and Pilatus. Is this expected?

2021-12-03 19:25 UTC, jfavre commented
I cannot reproduce the failure of the test on eiger and pilatus, They work fine for me:
reframe -c paraview_check.py -n ParaViewCheck --system pilatus:mc -r
[  PASSED  ] Ran 1/1 test case(s) from 1 check(s) (0 failure(s), 0 skipped)

reframe -c paraview_check.py -n ParaViewCheck --system eiger:mc -r
[  PASSED  ] Ran 1/1 test case(s) from 1 check(s) (0 failure(s), 0 skipped)

2021-12-06 17:52 UTC, vkarak commented
@jfavre It doesn't pass for me in a fresh login. I guess that you have a `ParaView` module already available in your `MODULEPATH`. The test passes if I load `cpeCray` first by doing `-S modules=cpeCray,ParaView`. I think that the `valid_prog_environs` should be `['cpeCray']` on Eiger/Pilatus and not `builtin`. Check the other applications.

2021-12-06 17:54 UTC, vkarak requested changes

2021-12-06 17:54 UTC, vkarak commented on cscs-checks/apps/paraview/paraview_check.py
> +    @run_after('setup')
Here is the bug. This should be a post-init hook:

```suggestion
    @run_after('init')
```

The reason for that is that after setup is too late for test filtering; the test has already started running (you can use `skip()` there, but it's much simpler if you just change the hook.

2021-12-06 23:35 UTC, vkarak approved these changes

2021-12-07 06:44 UTC, jfavre reviewed
looks good. thanks for clarifying

2021-12-07 07:50 UTC, merged