[test] Fix setting of environment variables in the numpy test
eth-cscs/reframe pull request #2300
Opened 2021-11-29 17:28 UTC by vkarak

Fixes #2297.

2021-11-29 17:36 UTC, rsarm approved these changes

2021-11-30 08:38 UTC, teojgo approved these changes

2021-11-30 13:52 UTC, teojgo requested changes

2021-11-30 13:52 UTC, teojgo commented on cscs-checks/apps/python/numpy_check.py
>              'OMP_NUM_THREADS': self.num_cpus_per_task
```suggestion
            'OMP_NUM_THREADS': str(self.num_cpus_per_task)
```

2021-11-30 13:54 UTC, teojgo approved these changes

2021-11-30 14:59 UTC, merged