[test] Update syntax of CPMD check
eth-cscs/reframe pull request #2349
Opened 2021-12-15 15:01 UTC by rsarm

2021-12-15 16:43 UTC, teojgo requested changes

2021-12-15 16:43 UTC, teojgo commented on cscs-checks/apps/cpmd/cpmd_check.py
> +        if self.scale == 'small':
Include the references in the first if block

2021-12-16 08:44 UTC, teojgo approved these changes

2021-12-16 12:04 UTC, vkarak requested changes
I have a minor comment. In the future, as soon as we have the new naming scheme we should consider replace the `scale` parameter with a `num_node`.

2021-12-16 12:04 UTC, vkarak commented on cscs-checks/apps/cpmd/cpmd_check.py
>              self.reference = {
I would rather add a reference dictionary at the class level with all the references and select here the valid set of references based on the variant. See how we've done it in other tests with `allref`.

2021-12-19 23:37 UTC, vkarak approved these changes

2021-12-20 13:23 UTC, merged