[test] Update syntax of CP2K check
eth-cscs/reframe pull request #2350
Opened 2021-12-15 16:40 UTC by rsarm

2021-12-15 16:48 UTC, teojgo requested changes

2021-12-15 16:48 UTC, teojgo commented on cscs-checks/apps/cp2k/cp2k_check.py
>          references = {
Put this in the class body

2021-12-16 08:44 UTC, teojgo approved these changes

2021-12-19 23:45 UTC, vkarak approved these changes
Generally, the test needs further refinement, such as making the CPU and GPU variants a parameter, rather than use two different classes. I'm approving so as to eliminate the deprecation warnings at least.

2021-12-20 20:16 UTC, merged