[bugfix] Set correctly numeric configuration parameters from the environment variables
eth-cscs/reframe pull request #2392
Opened 2022-01-20 09:48 UTC by ekouts

Fixes #2246.

2022-01-20 10:03 UTC, teojgo commented
Do you think that we could do something more generic, like adding a `type` option? https://docs.python.org/3/library/argparse.html#type

2022-01-20 12:44 UTC, vkarak commented
I agree with @teojgo, I was also thinking of something more generic.

2022-01-31 20:56 UTC, vkarak requested changes
I think there are more options that need conversion, e.g., `max_retries`. And we need a unit test. Also what happens if `type` is passed and no environment variable is associated with the option? Does the conversion still happen?

2022-01-31 20:56 UTC, vkarak commented on reframe/frontend/argparse.py
> +        envvar, _, action, cast_type = self.__option_map[name]
```suggestion
        envvar, _, action, arg_type = self.__option_map[name]
```

2022-01-31 20:56 UTC, vkarak commented on reframe/frontend/argparse.py
> +                        ) from None
```suggestion
                    except ValueError as err:
                        raise ValueError(
                            f'cannot convert environment variable {envvar!r} to {arg_type.__name__!r}'
                        ) from err
```

2022-01-31 20:56 UTC, vkarak commented on reframe/frontend/argparse.py
> +            _, confvar, action, _ = spec
```suggestion
            confvar, action = spec[1:3]
```

2022-02-03 09:25 UTC, ekouts commented
@vkarak I added the type to `max-retries` and `maxfail`. Let me know if I missed any other option. I also extended a bit the argparger unittests.
> Also what happens if type is passed and no environment variable is associated with the option? Does the conversion still happen?

No, it will not try to do any conversion if it the value is `None`.

2022-02-04 08:38 UTC, ekouts commented on reframe/frontend/cli.py
> +        max_retries = int(options.max_retries)
Sorry, you are right. I just changed the indentation and I didn't realize I was re-casting it.

2022-02-04 10:10 UTC, vkarak approved these changes

2022-02-04 10:11 UTC, merged