[bugfix] Fix `--show-config` for `null` config options
eth-cscs/reframe pull request #2414
Opened 2022-02-02 17:45 UTC by teojgo

Fixes #2388

2022-02-02 17:45 UTC, pep8speaks commented
Hello @teojgo, Thank you for submitting the Pull Request!



* In the file [`reframe/frontend/cli.py`](https://github.com/eth-cscs/reframe/blob/96a2f806c8772e81adad84a2b54a2ae9057af5ec/reframe/frontend/cli.py):

> [Line 772:80](https://github.com/eth-cscs/reframe/blob/96a2f806c8772e81adad84a2b54a2ae9057af5ec/reframe/frontend/cli.py#L772): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)

Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2022-02-02 18:15 UTC, vkarak requested changes
Just a minor adaptation. 

@mahendrapaipuri Could you check if this one fixes also #2360? I did a quick test with `--show-config` and seems to be ok.

2022-02-02 18:15 UTC, vkarak commented on reframe/frontend/cli.py
> +            if value == default:
Nice trick, but I would rather use another type of unique value:

```suggestion
            default = {'token'}
            value = rt.get_option(config_param, default)
            if value is default:
```

2022-02-03 09:14 UTC, mahendrapaipuri commented
@vkarak Sure. I would test this patch over the weekend.

2022-02-03 16:51 UTC, vkarak approved these changes

2022-02-07 09:27 UTC, merged