[test] Make parameters loggable in Amber and Gromacs tests
eth-cscs/reframe pull request #2449
Opened 2022-02-23 23:25 UTC by vkarak

2022-02-24 10:50 UTC, teojgo requested changes

2022-02-24 10:50 UTC, teojgo commented on hpctestlib/sciapps/amber/nve.py
>          self.descr = f'Amber NVE {self.benchmark} benchmark ({self.variant})'
```suggestion
        self.descr = f'Amber NVE {self.bench_name} benchmark ({self.variant})'
```

2022-02-24 15:40 UTC, teojgo commented on hpctestlib/sciapps/amber/nve.py
>          self.descr = f'Amber NVE {self.benchmark} benchmark ({self.variant})'
The same change is needed also on line 126.

2022-02-24 19:19 UTC, pep8speaks commented
Hello @vkarak, Thank you for updating!





* In the file [`hpctestlib/sciapps/amber/nve.py`](https://github.com/eth-cscs/reframe/blob/61244039f1622a0051382fc037b78c28ceb4e6bf/hpctestlib/sciapps/amber/nve.py):

> [Line 127:80](https://github.com/eth-cscs/reframe/blob/61244039f1622a0051382fc037b78c28ceb4e6bf/hpctestlib/sciapps/amber/nve.py#L127): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)



Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2022-02-25 12:52 UTC, victorusu approved these changes
`lgtm`

2022-02-26 21:11 UTC, vkarak commented
@jenkins-cscs retry dom

2022-02-28 07:54 UTC, teojgo approved these changes

2022-02-28 09:18 UTC, merged