[feat] Extend `Job` public API
eth-cscs/reframe pull request #2463
Opened 2022-03-05 22:44 UTC by vkarak

This PR exposes several `Job` attributes publicly by practically documenting them. It also uses the `variable` builtin to define them and also refactors a bit the arguments passed to the constructor of a `Job`. Now, the arguments that are passed to it are only those that must be set from the frontend either directly or indirectly through the configuration.

Fixes #2315.

2022-03-07 12:18 UTC, teojgo requested changes

2022-03-07 12:18 UTC, teojgo commented on reframe/core/pipeline.py
> +        self.exclusive_access = self.exclusive_access
Do you mean `self.job.exclusive_access`?

2022-03-08 08:26 UTC, ekouts approved these changes

2022-03-08 08:27 UTC, teojgo approved these changes

2022-03-08 09:46 UTC, merged