[bugfix] Fix test filtering by name for multiple exact names
eth-cscs/reframe pull request #2485
Opened 2022-03-29 14:57 UTC by teojgo

Fixes #2483

2022-03-29 15:44 UTC, ekouts requested changes
I think there is something wrong with the PR. No matter what I try all tests are listed when I pass `-n Foo@1` (even if there is no test Foo).

2022-03-29 20:24 UTC, vkarak requested changes

2022-03-29 20:24 UTC, vkarak commented on reframe/frontend/cli.py
> +            testcases = filter(_filter_multiple_names(names), testcases)
I think that we should rather introduce a separate filter just for matching the unique names. So you should split the names into `exact` and `regex` as you do now (in a single loop preferably), join the `regex_names` with `|` and use the current `have_name()` (but remove from it the logic about matching exact names) and then call another filter for matching any of the exact names.

2022-03-29 20:24 UTC, vkarak commented on unittests/test_cli.py
> +        more_options=['-t', 'foo', '-n', 'HelloTest', '-n', 'HelloMakeTest']
I don't think that this change tests what we want to test. We should test a combination of `-n Test` and `-n TestX@0` options.

2022-03-30 08:30 UTC, teojgo commented
> I think there is something wrong with the PR. No matter what I try all tests are listed when I pass `-n Foo@1` (even if there is no test Foo).

Indeed, thanks for checking, the problem is that even if `regex_names` is empty the `join` results in the empty string which matches everything after

2022-04-01 11:58 UTC, pep8speaks commented
Hello @teojgo, Thank you for updating!

* In the file [`reframe/frontend/cli.py`](https://github.com/eth-cscs/reframe/blob/f860a275ac42f23c740b3b746e3d1a80b9ccc71d/reframe/frontend/cli.py):

> [Line 926:80](https://github.com/eth-cscs/reframe/blob/f860a275ac42f23c740b3b746e3d1a80b9ccc71d/reframe/frontend/cli.py#L926): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)







Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)

2022-04-01 20:24 UTC, vkarak requested changes
I have created a new filter function that basically combines the two filtering functions that you have. I think that we still need to remove the `have_name` and replace `have_not_name` now.

2022-04-01 20:26 UTC, vkarak commented
With my suggestion we could also avoid the extra tests in the cli if we added unit tests for the new filtering function.

2022-04-05 06:42 UTC, ekouts approved these changes

2022-04-05 15:17 UTC, vkarak approved these changes

2022-04-05 15:19 UTC, merged